#cleaning mpcb 2024 data
source-- /content/drive/MyDrive/Amajor/img: inp- code- op/AQI_daily_2024_Bandra_Kurla_Complex_Mumbai_MPCB_2024.xlsx

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/AQI_daily_2024_Bandra_Kurla_Complex_Mumbai_MPCB_2024.xlsx")

In [ ]:
month_map = {
    "January": "JAN",
    "February": "FEB",
    "March": "MAR",
    "April": "APR",
    "May": "MAY",
    "June": "JUN",
    "July": "JUL",
    "August": "AUG",
    "September": "SEP",
    "October": "OCT",
    "November": "NOV",
    "December": "DEC"
}

df = df.rename(columns=month_map)

In [ ]:
df_long = df.melt(
    id_vars=["Day"],
    value_vars=list(month_map.values()),
    var_name="Month",
    value_name="AQI"
)
df2= df_long
df2 = df2[["Day", "Month", "AQI"]]

In [ ]:
#df2["Day"] = df2["Day"].astype(int)
df2["Month"] = df2["Month"].astype(str)
df2["AQI"] = df2["AQI"].astype(float)

print(df2.head())

  Day Month    AQI
0   1   JAN    NaN
1   2   JAN  151.0
2   3   JAN  136.0
3   4   JAN  154.0
4   5   JAN  180.0

In [ ]:
print(df2.to_string())

                   Day Month    AQI
0                    1   JAN    NaN
1                    2   JAN  151.0
2                    3   JAN  136.0
3                    4   JAN  154.0
4                    5   JAN  180.0
5                    6   JAN  205.0
6                    7   JAN  162.0
7                    8   JAN  105.0
8                    9   JAN  106.0
9                   10   JAN   79.0
10                  11   JAN  149.0
11                  12   JAN  171.0
12                  13   JAN  156.0
13                  14   JAN  134.0
14                  15   JAN  100.0
15                  16   JAN  108.0
16                  17   JAN  172.0
17                  18   JAN  156.0
18                  19   JAN  116.0
19                  20   JAN  226.0
20                  21   JAN  132.0
21                  22   JAN    NaN
22                  23   JAN  135.0
23                  24   JAN  138.0
24                  25   JAN  108.0
25                  26   JAN  150.0
26                  27   JAN   99.0
27                  28   JAN  171.0
28                  29   JAN  123.0
29                  30   JAN  144.0
30                  31   JAN  122.0
31                       JAN    NaN
32                Good   JAN    NaN
33        Satisfactory   JAN    3.0
34            Moderate   JAN   24.0
35                Poor   JAN    2.0
36           Very poor   JAN    NaN
37              Severe   JAN    NaN
38                 NaN   JAN    2.0
39                  SP   JAN    NaN
40   % of Availability   JAN   93.0
41                   1   FEB  106.0
42                   2   FEB   99.0
43                   3   FEB  165.0
44                   4   FEB  244.0
45                   5   FEB  239.0
46                   6   FEB  146.0
47                   7   FEB  134.0
48                   8   FEB  153.0
49                   9   FEB  158.0
50                  10   FEB  150.0
51                  11   FEB  158.0
52                  12   FEB  141.0
53                  13   FEB  167.0
54                  14   FEB  143.0
55                  15   FEB  205.0
56                  16   FEB    NaN
57                  17   FEB    NaN
58                  18   FEB  187.0
59                  19   FEB  131.0
60                  20   FEB  151.0
61                  21   FEB   83.0
62                  22   FEB  104.0
63                  23   FEB  127.0
64                  24   FEB  173.0
65                  25   FEB  211.0
66                  26   FEB  204.0
67                  27   FEB  198.0
68                  28   FEB  180.0
69                  29   FEB  192.0
70                  30   FEB    NaN
71                  31   FEB    NaN
72                       FEB    NaN
73                Good   FEB    NaN
74        Satisfactory   FEB    2.0
75            Moderate   FEB   20.0
76                Poor   FEB    5.0
77           Very poor   FEB    NaN
78              Severe   FEB    NaN
79                 NaN   FEB    2.0
80                  SP   FEB    NaN
81   % of Availability   FEB   93.0
82                   1   MAR  130.0
83                   2   MAR   88.0
84                   3   MAR   51.0
85                   4   MAR   61.0
86                   5   MAR  147.0
87                   6   MAR  165.0
88                   7   MAR  131.0
89                   8   MAR  170.0
90                   9   MAR  166.0
91                  10   MAR  137.0
92                  11   MAR  110.0
93                  12   MAR  130.0
94                  13   MAR   90.0
95                  14   MAR   82.0
96                  15   MAR  129.0
97                  16   MAR  165.0
98                  17   MAR  135.0
99                  18   MAR  126.0
100                 19   MAR  148.0
101                 20   MAR  162.0
102                 21   MAR  163.0
103                 22   MAR  186.0
104                 23   MAR  129.0
105                 24   MAR  101.0
106                 25   MAR   92.0
107                 26   MAR   88.0
108                 27   MAR  102.0
109                 28   MAR    NaN
110                 29   MAR  116.0
111                 30   MAR  118.0
112                 31   MAR  114.0
113                      MAR    NaN
114               Good   MAR    NaN
115       Satisfactory   MAR    7.0
116           Moderate   MAR   23.0
117               Poor   MAR    NaN
118          Very poor   MAR    NaN
119             Severe   MAR    NaN
120                NaN   MAR    1.0
121                 SP   MAR    NaN
122  % of Availability   MAR   96.0
123                  1   APR  113.0
124                  2   APR  205.0
125                  3   APR  153.0
126                  4   APR  100.0
127                  5   APR   90.0
128                  6   APR  124.0
129                  7   APR    NaN
130                  8   APR    NaN
131                  9   APR    NaN
132                 10   APR    NaN
133                 11   APR   97.0
134                 12   APR   88.0
135                 13   APR   86.0
136                 14   APR   91.0
137                 15   APR   85.0
138                 16   APR  158.0
139                 17   APR  129.0
140                 18   APR  106.0
141                 19   APR  102.0
142                 20   APR    NaN
143                 21   APR  110.0
144                 22   APR   64.0
145                 23   APR   96.0
146                 24   APR    NaN
147                 25   APR   92.0
148                 26   APR   74.0
149                 27   APR   94.0
150                 28   APR  245.0
151                 29   APR  114.0
152                 30   APR  123.0
153                 31   APR    NaN
154                      APR    NaN
155               Good   APR    NaN
156       Satisfactory   APR   12.0
157           Moderate   APR   10.0
158               Poor   APR    2.0
159          Very poor   APR    NaN
160             Severe   APR    NaN
161                NaN   APR    6.0
162                 SP   APR    NaN
163  % of Availability   APR   80.0
164                  1   MAY  108.0
165                  2   MAY   98.0
166                  3   MAY  135.0
167                  4   MAY   95.0
168                  5   MAY   82.0
169                  6   MAY   66.0
170                  7   MAY   67.0
171                  8   MAY   82.0
172                  9   MAY   71.0
173                 10   MAY   69.0
174                 11   MAY   85.0
175                 12   MAY   81.0
176                 13   MAY   73.0
177                 14   MAY  183.0
178                 15   MAY  177.0
179                 16   MAY  105.0
180                 17   MAY  131.0
181                 18   MAY  100.0
182                 19   MAY   97.0
183                 20   MAY   74.0
184                 21   MAY   77.0
185                 22   MAY   88.0
186                 23   MAY    NaN
187                 24   MAY    NaN
188                 25   MAY   86.0
189                 26   MAY   86.0
190                 27   MAY   79.0
191                 28   MAY   85.0
192                 29   MAY  106.0
193                 30   MAY  108.0
194                 31   MAY   89.0
195                      MAY    NaN
196               Good   MAY    NaN
197       Satisfactory   MAY   21.0
198           Moderate   MAY    8.0
199               Poor   MAY    NaN
200          Very poor   MAY    NaN
201             Severe   MAY    NaN
202                NaN   MAY    2.0
203                 SP   MAY    NaN
204  % of Availability   MAY   93.0
205                  1   JUN   78.0
206                  2   JUN   83.0
207                  3   JUN   76.0
208                  4   JUN  109.0
209                  5   JUN   81.0
210                  6   JUN   62.0
211                  7   JUN   85.0
212                  8   JUN   90.0
213                  9   JUN   67.0
214                 10   JUN   53.0
215                 11   JUN   50.0
216                 12   JUN   84.0
217                 13   JUN   80.0
218                 14   JUN   62.0
219                 15   JUN   76.0
220                 16   JUN   72.0
221                 17   JUN   77.0
222                 18   JUN    NaN
223                 19   JUN   49.0
224                 20   JUN   57.0
225                 21   JUN   65.0
226                 22   JUN   75.0
227                 23   JUN   84.0
228                 24   JUN   57.0
229                 25   JUN   79.0
230                 26   JUN   59.0
231                 27   JUN   38.0
232                 28   JUN   38.0
233                 29   JUN    NaN
234                 30   JUN   53.0
235                 31   JUN    NaN
236                      JUN    NaN
237               Good   JUN    4.0
238       Satisfactory   JUN   23.0
239           Moderate   JUN    1.0
240               Poor   JUN    NaN
241          Very poor   JUN    NaN
242             Severe   JUN    NaN
243                NaN   JUN    2.0
244                 SP   JUN    NaN
245  % of Availability   JUN   93.0
246                  1   JUL   62.0
247                  2   JUL   56.0
248                  3   JUL   92.0
249                  4   JUL   88.0
250                  5   JUL   70.0
251                  6   JUL   59.0
252                  7   JUL    NaN
253                  8   JUL    NaN
254                  9   JUL   54.0
255                 10   JUL   48.0
256                 11   JUL   46.0
257                 12   JUL   54.0
258                 13   JUL   42.0
259                 14   JUL   35.0
260                 15   JUL   58.0
261                 16   JUL   38.0
262                 17   JUL   48.0
263                 18   JUL   41.0
264                 19   JUL   39.0
265                 20   JUL   37.0
266                 21   JUL   31.0
267                 22   JUL   43.0
268                 23   JUL   38.0
269                 24   JUL   38.0
270                 25   JUL   41.0
271                 26   JUL   41.0
272                 27   JUL   50.0
273                 28   JUL   56.0
274                 29   JUL   56.0
275                 30   JUL   50.0
276                 31   JUL   58.0
277                      JUL    NaN
278               Good   JUL   17.0
279       Satisfactory   JUL   12.0
280           Moderate   JUL    NaN
281               Poor   JUL    NaN
282          Very poor   JUL    NaN
283             Severe   JUL    NaN
284                NaN   JUL    2.0
285                 SP   JUL    NaN
286  % of Availability   JUL   93.0
287                  1   AUG   50.0
288                  2   AUG   41.0
289                  3   AUG   33.0
290                  4   AUG   32.0
291                  5   AUG   41.0
292                  6   AUG   42.0
293                  7   AUG   40.0
294                  8   AUG   58.0
295                  9   AUG   59.0
296                 10   AUG   52.0
297                 11   AUG   40.0
298                 12   AUG   54.0
299                 13   AUG   66.0
300                 14   AUG   88.0
301                 15   AUG  102.0
302                 16   AUG   61.0
303                 17   AUG   84.0
304                 18   AUG   97.0
305                 19   AUG   69.0
306                 20   AUG   76.0
307                 21   AUG   93.0
308                 22   AUG   60.0
309                 23   AUG   61.0
310                 24   AUG   48.0
311                 25   AUG   44.0
312                 26   AUG    NaN
313                 27   AUG   46.0
314                 28   AUG    NaN
315                 29   AUG   62.0
316                 30   AUG    NaN
317                 31   AUG   95.0
318                      AUG    NaN
319               Good   AUG   11.0
320       Satisfactory   AUG   16.0
321           Moderate   AUG    1.0
322               Poor   AUG    NaN
323          Very poor   AUG    NaN
324             Severe   AUG    NaN
325                NaN   AUG    3.0
326                 SP   AUG    NaN
327  % of Availability   AUG   90.0
328                  1   SEP   60.0
329                  2   SEP   65.0
330                  3   SEP   48.0
331                  4   SEP   59.0
332                  5   SEP   40.0
333                  6   SEP   45.0
334                  7   SEP   43.0
335                  8   SEP    NaN
336                  9   SEP   53.0
337                 10   SEP   78.0
338                 11   SEP    NaN
339                 12   SEP   66.0
340                 13   SEP    NaN
341                 14   SEP   81.0
342                 15   SEP   91.0
343                 16   SEP  103.0
344                 17   SEP  121.0
345                 18   SEP   86.0
346                 19   SEP  116.0
347                 20   SEP  169.0
348                 21   SEP  135.0
349                 22   SEP  114.0
350                 23   SEP   80.0
351                 24   SEP   50.0
352                 25   SEP    NaN
353                 26   SEP   58.0
354                 27   SEP   49.0
355                 28   SEP   54.0
356                 29   SEP   51.0
357                 30   SEP   58.0
358                 31   SEP    NaN
359                      SEP    NaN
360               Good   SEP    6.0
361       Satisfactory   SEP   14.0
362           Moderate   SEP    6.0
363               Poor   SEP    NaN
364          Very poor   SEP    NaN
365             Severe   SEP    NaN
366                NaN   SEP    4.0
367                 SP   SEP    NaN
368  % of Availability   SEP   86.0
369                  1   OCT   79.0
370                  2   OCT  110.0
371                  3   OCT   64.0
372                  4   OCT   47.0
373                  5   OCT   98.0
374                  6   OCT  118.0
375                  7   OCT  115.0
376                  8   OCT  231.0
377                  9   OCT    NaN
378                 10   OCT    NaN
379                 11   OCT   78.0
380                 12   OCT   56.0
381                 13   OCT    NaN
382                 14   OCT    NaN
383                 15   OCT  117.0
384                 16   OCT  127.0
385                 17   OCT  127.0
386                 18   OCT  156.0
387                 19   OCT   65.0
388                 20   OCT   67.0
389                 21   OCT    NaN
390                 22   OCT  100.0
391                 23   OCT  109.0
392                 24   OCT  134.0
393                 25   OCT  165.0
394                 26   OCT  168.0
395                 27   OCT  146.0
396                 28   OCT  144.0
397                 29   OCT  106.0
398                 30   OCT  132.0
399                 31   OCT  201.0
400                      OCT    NaN
401               Good   OCT    1.0
402       Satisfactory   OCT    8.0
403           Moderate   OCT   15.0
404               Poor   OCT    2.0
405          Very poor   OCT    NaN
406             Severe   OCT    NaN
407                NaN   OCT    5.0
408                 SP   OCT    NaN
409  % of Availability   OCT   83.0
410                  1   NOV  194.0
411                  2   NOV  284.0
412                  3   NOV  196.0
413                  4   NOV  193.0
414                  5   NOV  222.0
415                  6   NOV  226.0
416                  7   NOV  193.0
417                  8   NOV  192.0
418                  9   NOV  173.0
419                 10   NOV  153.0
420                 11   NOV  162.0
421                 12   NOV  169.0
422                 13   NOV  158.0
423                 14   NOV  180.0
424                 15   NOV    NaN
425                 16   NOV  140.0
426                 17   NOV  260.0
427                 18   NOV  130.0
428                 19   NOV   87.0
429                 20   NOV  162.0
430                 21   NOV  197.0
431                 22   NOV  216.0
432                 23   NOV  231.0
433                 24   NOV  242.0
434                 25   NOV  227.0
435                 26   NOV  154.0
436                 27   NOV  154.0
437                 28   NOV  158.0
438                 29   NOV  162.0
439                 30   NOV  131.0
440                 31   NOV    NaN
441                      NOV    NaN
442               Good   NOV    NaN
443       Satisfactory   NOV    1.0
444           Moderate   NOV   20.0
445               Poor   NOV    8.0
446          Very poor   NOV    NaN
447             Severe   NOV    NaN
448                NaN   NOV    1.0
449                 SP   NOV    NaN
450  % of Availability   NOV   96.0
451                  1   DEC  147.0
452                  2   DEC  183.0
453                  3   DEC  141.0
454                  4   DEC  171.0
455                  5   DEC  180.0
456                  6   DEC  169.0
457                  7   DEC  139.0
458                  8   DEC  160.0
459                  9   DEC  118.0
460                 10   DEC  161.0
461                 11   DEC  177.0
462                 12   DEC  149.0
463                 13   DEC  152.0
464                 14   DEC  146.0
465                 15   DEC  164.0
466                 16   DEC  175.0
467                 17   DEC  199.0
468                 18   DEC  235.0
469                 19   DEC  164.0
470                 20   DEC  124.0
471                 21   DEC  205.0
472                 22   DEC  156.0
473                 23   DEC    NaN
474                 24   DEC  147.0
475                 25   DEC    NaN
476                 26   DEC  153.0
477                 27   DEC  152.0
478                 28   DEC  192.0
479                 29   DEC  194.0
480                 30   DEC  167.0
481                 31   DEC  162.0
482                      DEC    NaN
483               Good   DEC    NaN
484       Satisfactory   DEC    NaN
485           Moderate   DEC   27.0
486               Poor   DEC    2.0
487          Very poor   DEC    NaN
488             Severe   DEC    NaN
489                NaN   DEC    2.0
490                 SP   DEC    NaN
491  % of Availability   DEC   93.0

In [ ]:
df2['Day'] = pd.to_numeric(df2['Day'], errors='coerce')
df2 = df2.dropna(subset=['Day'])
df2['Day'] = df2['Day'].astype(int)

In [ ]:
print(df2.to_string())

     Day Month    AQI
0      1   JAN    NaN
1      2   JAN  151.0
2      3   JAN  136.0
3      4   JAN  154.0
4      5   JAN  180.0
5      6   JAN  205.0
6      7   JAN  162.0
7      8   JAN  105.0
8      9   JAN  106.0
9     10   JAN   79.0
10    11   JAN  149.0
11    12   JAN  171.0
12    13   JAN  156.0
13    14   JAN  134.0
14    15   JAN  100.0
15    16   JAN  108.0
16    17   JAN  172.0
17    18   JAN  156.0
18    19   JAN  116.0
19    20   JAN  226.0
20    21   JAN  132.0
21    22   JAN    NaN
22    23   JAN  135.0
23    24   JAN  138.0
24    25   JAN  108.0
25    26   JAN  150.0
26    27   JAN   99.0
27    28   JAN  171.0
28    29   JAN  123.0
29    30   JAN  144.0
30    31   JAN  122.0
41     1   FEB  106.0
42     2   FEB   99.0
43     3   FEB  165.0
44     4   FEB  244.0
45     5   FEB  239.0
46     6   FEB  146.0
47     7   FEB  134.0
48     8   FEB  153.0
49     9   FEB  158.0
50    10   FEB  150.0
51    11   FEB  158.0
52    12   FEB  141.0
53    13   FEB  167.0
54    14   FEB  143.0
55    15   FEB  205.0
56    16   FEB    NaN
57    17   FEB    NaN
58    18   FEB  187.0
59    19   FEB  131.0
60    20   FEB  151.0
61    21   FEB   83.0
62    22   FEB  104.0
63    23   FEB  127.0
64    24   FEB  173.0
65    25   FEB  211.0
66    26   FEB  204.0
67    27   FEB  198.0
68    28   FEB  180.0
69    29   FEB  192.0
70    30   FEB    NaN
71    31   FEB    NaN
82     1   MAR  130.0
83     2   MAR   88.0
84     3   MAR   51.0
85     4   MAR   61.0
86     5   MAR  147.0
87     6   MAR  165.0
88     7   MAR  131.0
89     8   MAR  170.0
90     9   MAR  166.0
91    10   MAR  137.0
92    11   MAR  110.0
93    12   MAR  130.0
94    13   MAR   90.0
95    14   MAR   82.0
96    15   MAR  129.0
97    16   MAR  165.0
98    17   MAR  135.0
99    18   MAR  126.0
100   19   MAR  148.0
101   20   MAR  162.0
102   21   MAR  163.0
103   22   MAR  186.0
104   23   MAR  129.0
105   24   MAR  101.0
106   25   MAR   92.0
107   26   MAR   88.0
108   27   MAR  102.0
109   28   MAR    NaN
110   29   MAR  116.0
111   30   MAR  118.0
112   31   MAR  114.0
123    1   APR  113.0
124    2   APR  205.0
125    3   APR  153.0
126    4   APR  100.0
127    5   APR   90.0
128    6   APR  124.0
129    7   APR    NaN
130    8   APR    NaN
131    9   APR    NaN
132   10   APR    NaN
133   11   APR   97.0
134   12   APR   88.0
135   13   APR   86.0
136   14   APR   91.0
137   15   APR   85.0
138   16   APR  158.0
139   17   APR  129.0
140   18   APR  106.0
141   19   APR  102.0
142   20   APR    NaN
143   21   APR  110.0
144   22   APR   64.0
145   23   APR   96.0
146   24   APR    NaN
147   25   APR   92.0
148   26   APR   74.0
149   27   APR   94.0
150   28   APR  245.0
151   29   APR  114.0
152   30   APR  123.0
153   31   APR    NaN
164    1   MAY  108.0
165    2   MAY   98.0
166    3   MAY  135.0
167    4   MAY   95.0
168    5   MAY   82.0
169    6   MAY   66.0
170    7   MAY   67.0
171    8   MAY   82.0
172    9   MAY   71.0
173   10   MAY   69.0
174   11   MAY   85.0
175   12   MAY   81.0
176   13   MAY   73.0
177   14   MAY  183.0
178   15   MAY  177.0
179   16   MAY  105.0
180   17   MAY  131.0
181   18   MAY  100.0
182   19   MAY   97.0
183   20   MAY   74.0
184   21   MAY   77.0
185   22   MAY   88.0
186   23   MAY    NaN
187   24   MAY    NaN
188   25   MAY   86.0
189   26   MAY   86.0
190   27   MAY   79.0
191   28   MAY   85.0
192   29   MAY  106.0
193   30   MAY  108.0
194   31   MAY   89.0
205    1   JUN   78.0
206    2   JUN   83.0
207    3   JUN   76.0
208    4   JUN  109.0
209    5   JUN   81.0
210    6   JUN   62.0
211    7   JUN   85.0
212    8   JUN   90.0
213    9   JUN   67.0
214   10   JUN   53.0
215   11   JUN   50.0
216   12   JUN   84.0
217   13   JUN   80.0
218   14   JUN   62.0
219   15   JUN   76.0
220   16   JUN   72.0
221   17   JUN   77.0
222   18   JUN    NaN
223   19   JUN   49.0
224   20   JUN   57.0
225   21   JUN   65.0
226   22   JUN   75.0
227   23   JUN   84.0
228   24   JUN   57.0
229   25   JUN   79.0
230   26   JUN   59.0
231   27   JUN   38.0
232   28   JUN   38.0
233   29   JUN    NaN
234   30   JUN   53.0
235   31   JUN    NaN
246    1   JUL   62.0
247    2   JUL   56.0
248    3   JUL   92.0
249    4   JUL   88.0
250    5   JUL   70.0
251    6   JUL   59.0
252    7   JUL    NaN
253    8   JUL    NaN
254    9   JUL   54.0
255   10   JUL   48.0
256   11   JUL   46.0
257   12   JUL   54.0
258   13   JUL   42.0
259   14   JUL   35.0
260   15   JUL   58.0
261   16   JUL   38.0
262   17   JUL   48.0
263   18   JUL   41.0
264   19   JUL   39.0
265   20   JUL   37.0
266   21   JUL   31.0
267   22   JUL   43.0
268   23   JUL   38.0
269   24   JUL   38.0
270   25   JUL   41.0
271   26   JUL   41.0
272   27   JUL   50.0
273   28   JUL   56.0
274   29   JUL   56.0
275   30   JUL   50.0
276   31   JUL   58.0
287    1   AUG   50.0
288    2   AUG   41.0
289    3   AUG   33.0
290    4   AUG   32.0
291    5   AUG   41.0
292    6   AUG   42.0
293    7   AUG   40.0
294    8   AUG   58.0
295    9   AUG   59.0
296   10   AUG   52.0
297   11   AUG   40.0
298   12   AUG   54.0
299   13   AUG   66.0
300   14   AUG   88.0
301   15   AUG  102.0
302   16   AUG   61.0
303   17   AUG   84.0
304   18   AUG   97.0
305   19   AUG   69.0
306   20   AUG   76.0
307   21   AUG   93.0
308   22   AUG   60.0
309   23   AUG   61.0
310   24   AUG   48.0
311   25   AUG   44.0
312   26   AUG    NaN
313   27   AUG   46.0
314   28   AUG    NaN
315   29   AUG   62.0
316   30   AUG    NaN
317   31   AUG   95.0
328    1   SEP   60.0
329    2   SEP   65.0
330    3   SEP   48.0
331    4   SEP   59.0
332    5   SEP   40.0
333    6   SEP   45.0
334    7   SEP   43.0
335    8   SEP    NaN
336    9   SEP   53.0
337   10   SEP   78.0
338   11   SEP    NaN
339   12   SEP   66.0
340   13   SEP    NaN
341   14   SEP   81.0
342   15   SEP   91.0
343   16   SEP  103.0
344   17   SEP  121.0
345   18   SEP   86.0
346   19   SEP  116.0
347   20   SEP  169.0
348   21   SEP  135.0
349   22   SEP  114.0
350   23   SEP   80.0
351   24   SEP   50.0
352   25   SEP    NaN
353   26   SEP   58.0
354   27   SEP   49.0
355   28   SEP   54.0
356   29   SEP   51.0
357   30   SEP   58.0
358   31   SEP    NaN
369    1   OCT   79.0
370    2   OCT  110.0
371    3   OCT   64.0
372    4   OCT   47.0
373    5   OCT   98.0
374    6   OCT  118.0
375    7   OCT  115.0
376    8   OCT  231.0
377    9   OCT    NaN
378   10   OCT    NaN
379   11   OCT   78.0
380   12   OCT   56.0
381   13   OCT    NaN
382   14   OCT    NaN
383   15   OCT  117.0
384   16   OCT  127.0
385   17   OCT  127.0
386   18   OCT  156.0
387   19   OCT   65.0
388   20   OCT   67.0
389   21   OCT    NaN
390   22   OCT  100.0
391   23   OCT  109.0
392   24   OCT  134.0
393   25   OCT  165.0
394   26   OCT  168.0
395   27   OCT  146.0
396   28   OCT  144.0
397   29   OCT  106.0
398   30   OCT  132.0
399   31   OCT  201.0
410    1   NOV  194.0
411    2   NOV  284.0
412    3   NOV  196.0
413    4   NOV  193.0
414    5   NOV  222.0
415    6   NOV  226.0
416    7   NOV  193.0
417    8   NOV  192.0
418    9   NOV  173.0
419   10   NOV  153.0
420   11   NOV  162.0
421   12   NOV  169.0
422   13   NOV  158.0
423   14   NOV  180.0
424   15   NOV    NaN
425   16   NOV  140.0
426   17   NOV  260.0
427   18   NOV  130.0
428   19   NOV   87.0
429   20   NOV  162.0
430   21   NOV  197.0
431   22   NOV  216.0
432   23   NOV  231.0
433   24   NOV  242.0
434   25   NOV  227.0
435   26   NOV  154.0
436   27   NOV  154.0
437   28   NOV  158.0
438   29   NOV  162.0
439   30   NOV  131.0
440   31   NOV    NaN
451    1   DEC  147.0
452    2   DEC  183.0
453    3   DEC  141.0
454    4   DEC  171.0
455    5   DEC  180.0
456    6   DEC  169.0
457    7   DEC  139.0
458    8   DEC  160.0
459    9   DEC  118.0
460   10   DEC  161.0
461   11   DEC  177.0
462   12   DEC  149.0
463   13   DEC  152.0
464   14   DEC  146.0
465   15   DEC  164.0
466   16   DEC  175.0
467   17   DEC  199.0
468   18   DEC  235.0
469   19   DEC  164.0
470   20   DEC  124.0
471   21   DEC  205.0
472   22   DEC  156.0
473   23   DEC    NaN
474   24   DEC  147.0
475   25   DEC    NaN
476   26   DEC  153.0
477   27   DEC  152.0
478   28   DEC  192.0
479   29   DEC  194.0
480   30   DEC  167.0
481   31   DEC  162.0

In [ ]:
df2.isna().sum()

Day       0
Month     0
AQI      38
dtype: int64

In [ ]:
'''drop illegal dates fr 2024,
29, 30 feb,
31 apr, jun, sept, nov
'''

'drop illegal dates fr 2024, \n29, 30 feb, \n31 apr, jun, sept, nov\n'

In [ ]:
df2.drop(
    df2[
        (df2['Month'] == 'FEB') &
        (df2['Day'].isin([29, 30]))
    ].index,
    inplace=True
)
df2.drop(
    df2[
        (df2['Month'].isin(['APR', 'JUN', 'SEP', 'NOV'])) &
        (df2['Day'] == 31)
    ].index,
    inplace=True
)

In [ ]:
df2.isna().sum()

Day       0
Month     0
AQI      33
dtype: int64

In [ ]:
df2.ffill(inplace=True)

In [ ]:
df2.isna().sum()

Day      0
Month    0
AQI      1
dtype: int64

In [ ]:
df2.bfill(inplace=True)

In [ ]:
df2.isna().sum()

Day      0
Month    0
AQI      0
dtype: int64

In [ ]:
output_path = '/content/drive/MyDrive/Amajor/img_summ/mcpb2024BKC.csv'
df2.to_csv(output_path, index=False)
print(f"DataFrame saved to {output_path}")

DataFrame saved to /content/drive/MyDrive/Amajor/img_summ/mcpb2024BKC.csv

#cleaning mpcb 2023 data
source-- /content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/AQI_daily_city_level_mumbai_2023_mumbai_2023.xlsx

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_excel('/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/AQI_daily_city_level_mumbai_2023_mumbai_2023.xlsx')

In [ ]:
df.head()

,Day,January,February,March,April,May,June,July,August,September,October,November,December
0,1,147.0,227.0,174.0,108.0,74.0,89.0,67.0,54.0,84.0,87.0,175.0,127.0
1,2,188.0,180.0,205.0,93.0,78.0,84.0,54.0,58.0,81.0,97.0,169.0,138.0
2,3,214.0,198.0,262.0,86.0,80.0,74.0,62.0,62.0,80.0,116.0,178.0,144.0
3,4,204.0,201.0,281.0,86.0,76.0,72.0,65.0,73.0,86.0,121.0,180.0,128.0
4,5,223.0,226.0,260.0,87.0,75.0,73.0,65.0,62.0,81.0,120.0,198.0,136.0

In [ ]:
month_map = {
    "January": "JAN",
    "February": "FEB",
    "March": "MAR",
    "April": "APR",
    "May": "MAY",
    "June": "JUN",
    "July": "JUL",
    "August": "AUG",
    "September": "SEP",
    "October": "OCT",
    "November": "NOV",
    "December": "DEC"
}

df = df.rename(columns=month_map)

df_long = df.melt(
    id_vars=["Day"],
    value_vars=list(month_map.values()),
    var_name="Month",
    value_name="AQI"
)
df2= df_long
df2 = df2[["Day", "Month", "AQI"]]

#df2["Day"] = df2["Day"].astype(int)
df2["Month"] = df2["Month"].astype(str)
df2["AQI"] = df2["AQI"].astype(float)

print(df2.head())

  Day Month    AQI
0   1   JAN  147.0
1   2   JAN  188.0
2   3   JAN  214.0
3   4   JAN  204.0
4   5   JAN  223.0

In [ ]:
print(df2.to_string())

                   Day Month    AQI
0                    1   JAN  147.0
1                    2   JAN  188.0
2                    3   JAN  214.0
3                    4   JAN  204.0
4                    5   JAN  223.0
5                    6   JAN  255.0
6                    7   JAN  204.0
7                    8   JAN  198.0
8                    9   JAN  137.0
9                   10   JAN  158.0
10                  11   JAN  213.0
11                  12   JAN  196.0
12                  13   JAN  134.0
13                  14   JAN  240.0
14                  15   JAN  198.0
15                  16   JAN  214.0
16                  17   JAN  236.0
17                  18   JAN  264.0
18                  19   JAN  256.0
19                  20   JAN  231.0
20                  21   JAN  175.0
21                  22   JAN  168.0
22                  23   JAN  170.0
23                  24   JAN  175.0
24                  25   JAN  209.0
25                  26   JAN  232.0
26                  27   JAN  254.0
27                  28   JAN  244.0
28                  29   JAN  176.0
29                  30   JAN  154.0
30                  31   JAN  225.0
31                       JAN    NaN
32                Good   JAN    NaN
33        Satisfactory   JAN    NaN
34            Moderate   JAN   14.0
35                Poor   JAN   17.0
36           Very poor   JAN    NaN
37              Severe   JAN    NaN
38                 NaN   JAN    NaN
39                  SP   JAN    NaN
40   % of Availability   JAN  100.0
41                   1   FEB  227.0
42                   2   FEB  180.0
43                   3   FEB  198.0
44                   4   FEB  201.0
45                   5   FEB  226.0
46                   6   FEB  185.0
47                   7   FEB  177.0
48                   8   FEB  233.0
49                   9   FEB  236.0
50                  10   FEB  200.0
51                  11   FEB  172.0
52                  12   FEB  165.0
53                  13   FEB  146.0
54                  14   FEB  203.0
55                  15   FEB  224.0
56                  16   FEB  199.0
57                  17   FEB  201.0
58                  18   FEB  185.0
59                  19   FEB  191.0
60                  20   FEB  183.0
61                  21   FEB  201.0
62                  22   FEB  123.0
63                  23   FEB  172.0
64                  24   FEB  219.0
65                  25   FEB  197.0
66                  26   FEB  208.0
67                  27   FEB  194.0
68                  28   FEB  188.0
69                  29   FEB    NaN
70                  30   FEB    NaN
71                  31   FEB    NaN
72                       FEB    NaN
73                Good   FEB    NaN
74        Satisfactory   FEB    NaN
75            Moderate   FEB   17.0
76                Poor   FEB   11.0
77           Very poor   FEB    NaN
78              Severe   FEB    NaN
79                 NaN   FEB    NaN
80                  SP   FEB    NaN
81   % of Availability   FEB  100.0
82                   1   MAR  174.0
83                   2   MAR  205.0
84                   3   MAR  262.0
85                   4   MAR  281.0
86                   5   MAR  260.0
87                   6   MAR  246.0
88                   7   MAR  139.0
89                   8   MAR  136.0
90                   9   MAR  156.0
91                  10   MAR  145.0
92                  11   MAR  163.0
93                  12   MAR  186.0
94                  13   MAR  213.0
95                  14   MAR  199.0
96                  15   MAR  165.0
97                  16   MAR  146.0
98                  17   MAR  117.0
99                  18   MAR  118.0
100                 19   MAR   97.0
101                 20   MAR   90.0
102                 21   MAR   91.0
103                 22   MAR   96.0
104                 23   MAR   86.0
105                 24   MAR   73.0
106                 25   MAR   88.0
107                 26   MAR   98.0
108                 27   MAR   97.0
109                 28   MAR  117.0
110                 29   MAR  125.0
111                 30   MAR  106.0
112                 31   MAR   82.0
113                      MAR    NaN
114               Good   MAR    NaN
115       Satisfactory   MAR   10.0
116           Moderate   MAR   15.0
117               Poor   MAR    6.0
118          Very poor   MAR    NaN
119             Severe   MAR    NaN
120                NaN   MAR    NaN
121                 SP   MAR    NaN
122  % of Availability   MAR  100.0
123                  1   APR  108.0
124                  2   APR   93.0
125                  3   APR   86.0
126                  4   APR   86.0
127                  5   APR   87.0
128                  6   APR   99.0
129                  7   APR  149.0
130                  8   APR  182.0
131                  9   APR  156.0
132                 10   APR  132.0
133                 11   APR  112.0
134                 12   APR  134.0
135                 13   APR  130.0
136                 14   APR  126.0
137                 15   APR  110.0
138                 16   APR  100.0
139                 17   APR   95.0
140                 18   APR  103.0
141                 19   APR  125.0
142                 20   APR  106.0
143                 21   APR   79.0
144                 22   APR   74.0
145                 23   APR   86.0
146                 24   APR   77.0
147                 25   APR  101.0
148                 26   APR   94.0
149                 27   APR   92.0
150                 28   APR   71.0
151                 29   APR   81.0
152                 30   APR   81.0
153                 31   APR    NaN
154                      APR    NaN
155               Good   APR    NaN
156       Satisfactory   APR   16.0
157           Moderate   APR   14.0
158               Poor   APR    NaN
159          Very poor   APR    NaN
160             Severe   APR    NaN
161                NaN   APR    NaN
162                 SP   APR    NaN
163  % of Availability   APR  100.0
164                  1   MAY   74.0
165                  2   MAY   78.0
166                  3   MAY   80.0
167                  4   MAY   76.0
168                  5   MAY   75.0
169                  6   MAY   74.0
170                  7   MAY   84.0
171                  8   MAY   82.0
172                  9   MAY   91.0
173                 10   MAY  112.0
174                 11   MAY  121.0
175                 12   MAY  120.0
176                 13   MAY   99.0
177                 14   MAY   52.0
178                 15   MAY   68.0
179                 16   MAY   67.0
180                 17   MAY   69.0
181                 18   MAY   75.0
182                 19   MAY   76.0
183                 20   MAY   80.0
184                 21   MAY   73.0
185                 22   MAY   70.0
186                 23   MAY   79.0
187                 24   MAY   69.0
188                 25   MAY   68.0
189                 26   MAY   67.0
190                 27   MAY   73.0
191                 28   MAY   75.0
192                 29   MAY   78.0
193                 30   MAY   80.0
194                 31   MAY   97.0
195                      MAY    NaN
196               Good   MAY    NaN
197       Satisfactory   MAY   28.0
198           Moderate   MAY    3.0
199               Poor   MAY    NaN
200          Very poor   MAY    NaN
201             Severe   MAY    NaN
202                NaN   MAY    NaN
203                 SP   MAY    NaN
204  % of Availability   MAY  100.0
205                  1   JUN   89.0
206                  2   JUN   84.0
207                  3   JUN   74.0
208                  4   JUN   72.0
209                  5   JUN   73.0
210                  6   JUN   81.0
211                  7   JUN   87.0
212                  8   JUN   89.0
213                  9   JUN   81.0
214                 10   JUN   85.0
215                 11   JUN   85.0
216                 12   JUN   90.0
217                 13   JUN   83.0
218                 14   JUN   78.0
219                 15   JUN   83.0
220                 16   JUN   84.0
221                 17   JUN   89.0
222                 18   JUN   98.0
223                 19   JUN   92.0
224                 20   JUN   93.0
225                 21   JUN  100.0
226                 22   JUN   97.0
227                 23   JUN   77.0
228                 24   JUN   73.0
229                 25   JUN   61.0
230                 26   JUN   73.0
231                 27   JUN   58.0
232                 28   JUN   61.0
233                 29   JUN   53.0
234                 30   JUN   56.0
235                 31   JUN    NaN
236                      JUN    NaN
237               Good   JUN    NaN
238       Satisfactory   JUN   30.0
239           Moderate   JUN    NaN
240               Poor   JUN    NaN
241          Very poor   JUN    NaN
242             Severe   JUN    NaN
243                NaN   JUN    NaN
244                 SP   JUN    NaN
245  % of Availability   JUN  100.0
246                  1   JUL   67.0
247                  2   JUL   54.0
248                  3   JUL   62.0
249                  4   JUL   65.0
250                  5   JUL   65.0
251                  6   JUL   51.0
252                  7   JUL   54.0
253                  8   JUL   91.0
254                  9   JUL   70.0
255                 10   JUL   65.0
256                 11   JUL   73.0
257                 12   JUL   77.0
258                 13   JUL  108.0
259                 14   JUL   87.0
260                 15   JUL   82.0
261                 16   JUL   87.0
262                 17   JUL   83.0
263                 18   JUL   80.0
264                 19   JUL   86.0
265                 20   JUL   86.0
266                 21   JUL   87.0
267                 22   JUL   88.0
268                 23   JUL   88.0
269                 24   JUL   87.0
270                 25   JUL   81.0
271                 26   JUL   48.0
272                 27   JUL   45.0
273                 28   JUL   49.0
274                 29   JUL   51.0
275                 30   JUL   52.0
276                 31   JUL   53.0
277                      JUL    NaN
278               Good   JUL    3.0
279       Satisfactory   JUL   27.0
280           Moderate   JUL    1.0
281               Poor   JUL    NaN
282          Very poor   JUL    NaN
283             Severe   JUL    NaN
284                NaN   JUL    NaN
285                 SP   JUL    NaN
286  % of Availability   JUL  100.0
287                  1   AUG   54.0
288                  2   AUG   58.0
289                  3   AUG   62.0
290                  4   AUG   73.0
291                  5   AUG   62.0
292                  6   AUG   68.0
293                  7   AUG   70.0
294                  8   AUG   71.0
295                  9   AUG   78.0
296                 10   AUG   65.0
297                 11   AUG   61.0
298                 12   AUG   65.0
299                 13   AUG   68.0
300                 14   AUG   67.0
301                 15   AUG   62.0
302                 16   AUG   56.0
303                 17   AUG   55.0
304                 18   AUG   55.0
305                 19   AUG   50.0
306                 20   AUG   53.0
307                 21   AUG   51.0
308                 22   AUG   50.0
309                 23   AUG   52.0
310                 24   AUG   53.0
311                 25   AUG   54.0
312                 26   AUG   61.0
313                 27   AUG   60.0
314                 28   AUG   56.0
315                 29   AUG   64.0
316                 30   AUG   87.0
317                 31   AUG   91.0
318                      AUG    NaN
319               Good   AUG    2.0
320       Satisfactory   AUG   29.0
321           Moderate   AUG    NaN
322               Poor   AUG    NaN
323          Very poor   AUG    NaN
324             Severe   AUG    NaN
325                NaN   AUG    NaN
326                 SP   AUG    NaN
327  % of Availability   AUG  100.0
328                  1   SEP   84.0
329                  2   SEP   81.0
330                  3   SEP   80.0
331                  4   SEP   86.0
332                  5   SEP   81.0
333                  6   SEP   78.0
334                  7   SEP   71.0
335                  8   SEP   65.0
336                  9   SEP   61.0
337                 10   SEP   54.0
338                 11   SEP   54.0
339                 12   SEP   59.0
340                 13   SEP   58.0
341                 14   SEP   63.0
342                 15   SEP   65.0
343                 16   SEP   60.0
344                 17   SEP   57.0
345                 18   SEP   58.0
346                 19   SEP   53.0
347                 20   SEP   51.0
348                 21   SEP   59.0
349                 22   SEP   59.0
350                 23   SEP   58.0
351                 24   SEP   53.0
352                 25   SEP   59.0
353                 26   SEP   67.0
354                 27   SEP   68.0
355                 28   SEP   77.0
356                 29   SEP   94.0
357                 30   SEP   72.0
358                 31   SEP    NaN
359                      SEP    NaN
360               Good   SEP    NaN
361       Satisfactory   SEP   30.0
362           Moderate   SEP    NaN
363               Poor   SEP    NaN
364          Very poor   SEP    NaN
365             Severe   SEP    NaN
366                NaN   SEP    NaN
367                 SP   SEP    NaN
368  % of Availability   SEP  100.0
369                  1   OCT   87.0
370                  2   OCT   97.0
371                  3   OCT  116.0
372                  4   OCT  121.0
373                  5   OCT  120.0
374                  6   OCT  131.0
375                  7   OCT  120.0
376                  8   OCT  110.0
377                  9   OCT  144.0
378                 10   OCT  109.0
379                 11   OCT   88.0
380                 12   OCT  100.0
381                 13   OCT  159.0
382                 14   OCT  177.0
383                 15   OCT  150.0
384                 16   OCT  185.0
385                 17   OCT  189.0
386                 18   OCT  199.0
387                 19   OCT  156.0
388                 20   OCT  185.0
389                 21   OCT  155.0
390                 22   OCT  172.0
391                 23   OCT  177.0
392                 24   OCT  182.0
393                 25   OCT  157.0
394                 26   OCT  157.0
395                 27   OCT  139.0
396                 28   OCT  153.0
397                 29   OCT  152.0
398                 30   OCT  157.0
399                 31   OCT  168.0
400                      OCT    NaN
401               Good   OCT    NaN
402       Satisfactory   OCT    4.0
403           Moderate   OCT   27.0
404               Poor   OCT    NaN
405          Very poor   OCT    NaN
406             Severe   OCT    NaN
407                NaN   OCT    NaN
408                 SP   OCT    NaN
409  % of Availability   OCT  100.0
410                  1   NOV  175.0
411                  2   NOV  169.0
412                  3   NOV  178.0
413                  4   NOV  180.0
414                  5   NOV  198.0
415                  6   NOV  198.0
416                  7   NOV  186.0
417                  8   NOV  131.0
418                  9   NOV  111.0
419                 10   NOV   87.0
420                 11   NOV   90.0
421                 12   NOV  154.0
422                 13   NOV  193.0
423                 14   NOV  168.0
424                 15   NOV  201.0
425                 16   NOV  168.0
426                 17   NOV  140.0
427                 18   NOV  162.0
428                 19   NOV  159.0
429                 20   NOV  115.0
430                 21   NOV  132.0
431                 22   NOV  123.0
432                 23   NOV  137.0
433                 24   NOV  152.0
434                 25   NOV  124.0
435                 26   NOV   98.0
436                 27   NOV   59.0
437                 28   NOV   61.0
438                 29   NOV   94.0
439                 30   NOV  102.0
440                 31   NOV    NaN
441                      NOV    NaN
442               Good   NOV    NaN
443       Satisfactory   NOV    6.0
444           Moderate   NOV   23.0
445               Poor   NOV    1.0
446          Very poor   NOV    NaN
447             Severe   NOV    NaN
448                NaN   NOV    NaN
449                 SP   NOV    NaN
450  % of Availability   NOV  100.0
451                  1   DEC  127.0
452                  2   DEC  138.0
453                  3   DEC  144.0
454                  4   DEC  128.0
455                  5   DEC  136.0
456                  6   DEC  154.0
457                  7   DEC  125.0
458                  8   DEC  117.0
459                  9   DEC  114.0
460                 10   DEC  114.0
461                 11   DEC  108.0
462                 12   DEC  114.0
463                 13   DEC  115.0
464                 14   DEC  134.0
465                 15   DEC  139.0
466                 16   DEC  133.0
467                 17   DEC  126.0
468                 18   DEC  136.0
469                 19   DEC  138.0
470                 20   DEC  134.0
471                 21   DEC  157.0
472                 22   DEC  189.0
473                 23   DEC  190.0
474                 24   DEC  166.0
475                 25   DEC  155.0
476                 26   DEC  178.0
477                 27   DEC  174.0
478                 28   DEC  194.0
479                 29   DEC  181.0
480                 30   DEC  161.0
481                 31   DEC  143.0
482                      DEC    NaN
483               Good   DEC    NaN
484       Satisfactory   DEC    NaN
485           Moderate   DEC   31.0
486               Poor   DEC    NaN
487          Very poor   DEC    NaN
488             Severe   DEC    NaN
489                NaN   DEC    NaN
490                 SP   DEC    NaN
491  % of Availability   DEC  100.0

In [ ]:
df2['Day'] = pd.to_numeric(df2['Day'], errors='coerce')
df2 = df2.dropna(subset=['Day'])
df2['Day'] = df2['Day'].astype(int)

In [ ]:
print(df2.to_string())

     Day Month    AQI
0      1   JAN  147.0
1      2   JAN  188.0
2      3   JAN  214.0
3      4   JAN  204.0
4      5   JAN  223.0
5      6   JAN  255.0
6      7   JAN  204.0
7      8   JAN  198.0
8      9   JAN  137.0
9     10   JAN  158.0
10    11   JAN  213.0
11    12   JAN  196.0
12    13   JAN  134.0
13    14   JAN  240.0
14    15   JAN  198.0
15    16   JAN  214.0
16    17   JAN  236.0
17    18   JAN  264.0
18    19   JAN  256.0
19    20   JAN  231.0
20    21   JAN  175.0
21    22   JAN  168.0
22    23   JAN  170.0
23    24   JAN  175.0
24    25   JAN  209.0
25    26   JAN  232.0
26    27   JAN  254.0
27    28   JAN  244.0
28    29   JAN  176.0
29    30   JAN  154.0
30    31   JAN  225.0
41     1   FEB  227.0
42     2   FEB  180.0
43     3   FEB  198.0
44     4   FEB  201.0
45     5   FEB  226.0
46     6   FEB  185.0
47     7   FEB  177.0
48     8   FEB  233.0
49     9   FEB  236.0
50    10   FEB  200.0
51    11   FEB  172.0
52    12   FEB  165.0
53    13   FEB  146.0
54    14   FEB  203.0
55    15   FEB  224.0
56    16   FEB  199.0
57    17   FEB  201.0
58    18   FEB  185.0
59    19   FEB  191.0
60    20   FEB  183.0
61    21   FEB  201.0
62    22   FEB  123.0
63    23   FEB  172.0
64    24   FEB  219.0
65    25   FEB  197.0
66    26   FEB  208.0
67    27   FEB  194.0
68    28   FEB  188.0
69    29   FEB    NaN
70    30   FEB    NaN
71    31   FEB    NaN
82     1   MAR  174.0
83     2   MAR  205.0
84     3   MAR  262.0
85     4   MAR  281.0
86     5   MAR  260.0
87     6   MAR  246.0
88     7   MAR  139.0
89     8   MAR  136.0
90     9   MAR  156.0
91    10   MAR  145.0
92    11   MAR  163.0
93    12   MAR  186.0
94    13   MAR  213.0
95    14   MAR  199.0
96    15   MAR  165.0
97    16   MAR  146.0
98    17   MAR  117.0
99    18   MAR  118.0
100   19   MAR   97.0
101   20   MAR   90.0
102   21   MAR   91.0
103   22   MAR   96.0
104   23   MAR   86.0
105   24   MAR   73.0
106   25   MAR   88.0
107   26   MAR   98.0
108   27   MAR   97.0
109   28   MAR  117.0
110   29   MAR  125.0
111   30   MAR  106.0
112   31   MAR   82.0
123    1   APR  108.0
124    2   APR   93.0
125    3   APR   86.0
126    4   APR   86.0
127    5   APR   87.0
128    6   APR   99.0
129    7   APR  149.0
130    8   APR  182.0
131    9   APR  156.0
132   10   APR  132.0
133   11   APR  112.0
134   12   APR  134.0
135   13   APR  130.0
136   14   APR  126.0
137   15   APR  110.0
138   16   APR  100.0
139   17   APR   95.0
140   18   APR  103.0
141   19   APR  125.0
142   20   APR  106.0
143   21   APR   79.0
144   22   APR   74.0
145   23   APR   86.0
146   24   APR   77.0
147   25   APR  101.0
148   26   APR   94.0
149   27   APR   92.0
150   28   APR   71.0
151   29   APR   81.0
152   30   APR   81.0
153   31   APR    NaN
164    1   MAY   74.0
165    2   MAY   78.0
166    3   MAY   80.0
167    4   MAY   76.0
168    5   MAY   75.0
169    6   MAY   74.0
170    7   MAY   84.0
171    8   MAY   82.0
172    9   MAY   91.0
173   10   MAY  112.0
174   11   MAY  121.0
175   12   MAY  120.0
176   13   MAY   99.0
177   14   MAY   52.0
178   15   MAY   68.0
179   16   MAY   67.0
180   17   MAY   69.0
181   18   MAY   75.0
182   19   MAY   76.0
183   20   MAY   80.0
184   21   MAY   73.0
185   22   MAY   70.0
186   23   MAY   79.0
187   24   MAY   69.0
188   25   MAY   68.0
189   26   MAY   67.0
190   27   MAY   73.0
191   28   MAY   75.0
192   29   MAY   78.0
193   30   MAY   80.0
194   31   MAY   97.0
205    1   JUN   89.0
206    2   JUN   84.0
207    3   JUN   74.0
208    4   JUN   72.0
209    5   JUN   73.0
210    6   JUN   81.0
211    7   JUN   87.0
212    8   JUN   89.0
213    9   JUN   81.0
214   10   JUN   85.0
215   11   JUN   85.0
216   12   JUN   90.0
217   13   JUN   83.0
218   14   JUN   78.0
219   15   JUN   83.0
220   16   JUN   84.0
221   17   JUN   89.0
222   18   JUN   98.0
223   19   JUN   92.0
224   20   JUN   93.0
225   21   JUN  100.0
226   22   JUN   97.0
227   23   JUN   77.0
228   24   JUN   73.0
229   25   JUN   61.0
230   26   JUN   73.0
231   27   JUN   58.0
232   28   JUN   61.0
233   29   JUN   53.0
234   30   JUN   56.0
235   31   JUN    NaN
246    1   JUL   67.0
247    2   JUL   54.0
248    3   JUL   62.0
249    4   JUL   65.0
250    5   JUL   65.0
251    6   JUL   51.0
252    7   JUL   54.0
253    8   JUL   91.0
254    9   JUL   70.0
255   10   JUL   65.0
256   11   JUL   73.0
257   12   JUL   77.0
258   13   JUL  108.0
259   14   JUL   87.0
260   15   JUL   82.0
261   16   JUL   87.0
262   17   JUL   83.0
263   18   JUL   80.0
264   19   JUL   86.0
265   20   JUL   86.0
266   21   JUL   87.0
267   22   JUL   88.0
268   23   JUL   88.0
269   24   JUL   87.0
270   25   JUL   81.0
271   26   JUL   48.0
272   27   JUL   45.0
273   28   JUL   49.0
274   29   JUL   51.0
275   30   JUL   52.0
276   31   JUL   53.0
287    1   AUG   54.0
288    2   AUG   58.0
289    3   AUG   62.0
290    4   AUG   73.0
291    5   AUG   62.0
292    6   AUG   68.0
293    7   AUG   70.0
294    8   AUG   71.0
295    9   AUG   78.0
296   10   AUG   65.0
297   11   AUG   61.0
298   12   AUG   65.0
299   13   AUG   68.0
300   14   AUG   67.0
301   15   AUG   62.0
302   16   AUG   56.0
303   17   AUG   55.0
304   18   AUG   55.0
305   19   AUG   50.0
306   20   AUG   53.0
307   21   AUG   51.0
308   22   AUG   50.0
309   23   AUG   52.0
310   24   AUG   53.0
311   25   AUG   54.0
312   26   AUG   61.0
313   27   AUG   60.0
314   28   AUG   56.0
315   29   AUG   64.0
316   30   AUG   87.0
317   31   AUG   91.0
328    1   SEP   84.0
329    2   SEP   81.0
330    3   SEP   80.0
331    4   SEP   86.0
332    5   SEP   81.0
333    6   SEP   78.0
334    7   SEP   71.0
335    8   SEP   65.0
336    9   SEP   61.0
337   10   SEP   54.0
338   11   SEP   54.0
339   12   SEP   59.0
340   13   SEP   58.0
341   14   SEP   63.0
342   15   SEP   65.0
343   16   SEP   60.0
344   17   SEP   57.0
345   18   SEP   58.0
346   19   SEP   53.0
347   20   SEP   51.0
348   21   SEP   59.0
349   22   SEP   59.0
350   23   SEP   58.0
351   24   SEP   53.0
352   25   SEP   59.0
353   26   SEP   67.0
354   27   SEP   68.0
355   28   SEP   77.0
356   29   SEP   94.0
357   30   SEP   72.0
358   31   SEP    NaN
369    1   OCT   87.0
370    2   OCT   97.0
371    3   OCT  116.0
372    4   OCT  121.0
373    5   OCT  120.0
374    6   OCT  131.0
375    7   OCT  120.0
376    8   OCT  110.0
377    9   OCT  144.0
378   10   OCT  109.0
379   11   OCT   88.0
380   12   OCT  100.0
381   13   OCT  159.0
382   14   OCT  177.0
383   15   OCT  150.0
384   16   OCT  185.0
385   17   OCT  189.0
386   18   OCT  199.0
387   19   OCT  156.0
388   20   OCT  185.0
389   21   OCT  155.0
390   22   OCT  172.0
391   23   OCT  177.0
392   24   OCT  182.0
393   25   OCT  157.0
394   26   OCT  157.0
395   27   OCT  139.0
396   28   OCT  153.0
397   29   OCT  152.0
398   30   OCT  157.0
399   31   OCT  168.0
410    1   NOV  175.0
411    2   NOV  169.0
412    3   NOV  178.0
413    4   NOV  180.0
414    5   NOV  198.0
415    6   NOV  198.0
416    7   NOV  186.0
417    8   NOV  131.0
418    9   NOV  111.0
419   10   NOV   87.0
420   11   NOV   90.0
421   12   NOV  154.0
422   13   NOV  193.0
423   14   NOV  168.0
424   15   NOV  201.0
425   16   NOV  168.0
426   17   NOV  140.0
427   18   NOV  162.0
428   19   NOV  159.0
429   20   NOV  115.0
430   21   NOV  132.0
431   22   NOV  123.0
432   23   NOV  137.0
433   24   NOV  152.0
434   25   NOV  124.0
435   26   NOV   98.0
436   27   NOV   59.0
437   28   NOV   61.0
438   29   NOV   94.0
439   30   NOV  102.0
440   31   NOV    NaN
451    1   DEC  127.0
452    2   DEC  138.0
453    3   DEC  144.0
454    4   DEC  128.0
455    5   DEC  136.0
456    6   DEC  154.0
457    7   DEC  125.0
458    8   DEC  117.0
459    9   DEC  114.0
460   10   DEC  114.0
461   11   DEC  108.0
462   12   DEC  114.0
463   13   DEC  115.0
464   14   DEC  134.0
465   15   DEC  139.0
466   16   DEC  133.0
467   17   DEC  126.0
468   18   DEC  136.0
469   19   DEC  138.0
470   20   DEC  134.0
471   21   DEC  157.0
472   22   DEC  189.0
473   23   DEC  190.0
474   24   DEC  166.0
475   25   DEC  155.0
476   26   DEC  178.0
477   27   DEC  174.0
478   28   DEC  194.0
479   29   DEC  181.0
480   30   DEC  161.0
481   31   DEC  143.0

In [ ]:
df2.drop(
    df2[
        (df2['Month'] == 'FEB') &
        (df2['Day'].isin([29, 30]))
    ].index,
    inplace=True
)
df2.drop(
    df2[
        (df2['Month'].isin(['APR', 'JUN', 'SEP', 'NOV'])) &
        (df2['Day'] == 31)
    ].index,
    inplace=True
)

In [ ]:
df2.isna().sum()

Day      0
Month    0
AQI      1
dtype: int64

In [ ]:
df2.ffill(inplace=True)
df2.bfill(inplace=True)

In [ ]:
df2.isna().sum()

Day      0
Month    0
AQI      0
dtype: int64

In [ ]:
output_path = '/content/drive/MyDrive/Amajor/img_summ/mcpb2023BKC.csv'
df2.to_csv(output_path, index=False)
print(f"DataFrame saved to {output_path}")

DataFrame saved to /content/drive/MyDrive/Amajor/img_summ/mcpb2023BKC.csv

#cleaning mpcb 2025 data

for jan-mar 2025

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

Mounted at /content/drive

In [ ]:
df= pd.read_excel('/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/AQI_daily_city_level_mumbai_2025_mumbai_2025 (1).xlsx')

In [ ]:
month_map = {
    "January": "JAN",
    "February": "FEB",
    "March": "MAR",
    "April": "APR",
    "May": "MAY",
    "June": "JUN",
    "July": "JUL",
    "August": "AUG",
    "September": "SEP",
    "October": "OCT",
    "November": "NOV",
    "December": "DEC"
}

df = df.rename(columns=month_map)

df_long = df.melt(
    id_vars=["Day"],
    value_vars=list(month_map.values()),
    var_name="Month",
    value_name="AQI"
)
df2= df_long
df2 = df2[["Day", "Month", "AQI"]]

#df2["Day"] = df2["Day"].astype(int)
df2["Month"] = df2["Month"].astype(str)
df2["AQI"] = df2["AQI"].astype(float)

print(df2.head())

  Day Month    AQI
0   1   JAN  140.0
1   2   JAN  119.0
2   3   JAN  126.0
3   4   JAN  154.0
4   5   JAN  162.0

In [ ]:
df2['Day'] = pd.to_numeric(df2['Day'], errors='coerce')
df2 = df2.dropna(subset=['Day'])
df2['Day'] = df2['Day'].astype(int)

In [ ]:
df2.drop(
    df2[
        (df2['Month'] == 'FEB') &
        (df2['Day'].isin([29, 30]))
    ].index,
    inplace=True
)

In [ ]:
df2.dropna(inplace=True)

In [ ]:
print(df2.to_string())

     Day Month    AQI
0      1   JAN  140.0
1      2   JAN  119.0
2      3   JAN  126.0
3      4   JAN  154.0
4      5   JAN  162.0
5      6   JAN  132.0
6      7   JAN  143.0
7      8   JAN  137.0
8      9   JAN  133.0
9     10   JAN  141.0
10    11   JAN  147.0
11    12   JAN  107.0
12    13   JAN  128.0
13    14   JAN  132.0
14    15   JAN  140.0
15    16   JAN  132.0
16    17   JAN  140.0
17    18   JAN  132.0
18    19   JAN  155.0
19    20   JAN  149.0
20    21   JAN  144.0
21    22   JAN  154.0
22    23   JAN  134.0
23    24   JAN  126.0
24    25   JAN  154.0
25    26   JAN  159.0
26    27   JAN  148.0
27    28   JAN  120.0
28    29   JAN  117.0
29    30   JAN  124.0
30    31   JAN  109.0
41     1   FEB   89.0
42     2   FEB  122.0
43     3   FEB  128.0
44     4   FEB  111.0
45     5   FEB  113.0
46     6   FEB  128.0
47     7   FEB  166.0
48     8   FEB  163.0
49     9   FEB  141.0
50    10   FEB  114.0
51    11   FEB  115.0
52    12   FEB  109.0
53    13   FEB  121.0
54    14   FEB  122.0
55    15   FEB  129.0
56    16   FEB  127.0
57    17   FEB   91.0
58    18   FEB  110.0
59    19   FEB  122.0
60    20   FEB  118.0
61    21   FEB  109.0
62    22   FEB  113.0
63    23   FEB  120.0
64    24   FEB  112.0
65    25   FEB  123.0
66    26   FEB  132.0
67    27   FEB  141.0
68    28   FEB  137.0
82     1   MAR  109.0
83     2   MAR  109.0
84     3   MAR  111.0
85     4   MAR  120.0
86     5   MAR  117.0
87     6   MAR  121.0
88     7   MAR  130.0
89     8   MAR  126.0
90     9   MAR   98.0
91    10   MAR  117.0
92    11   MAR  159.0
93    12   MAR  147.0
94    13   MAR  121.0
95    14   MAR  120.0
96    15   MAR   71.0
97    16   MAR   83.0
98    17   MAR  101.0
99    18   MAR   87.0
100   19   MAR   84.0
101   20   MAR   88.0
102   21   MAR   86.0
103   22   MAR   74.0
104   23   MAR   82.0
105   24   MAR   92.0
106   25   MAR   96.0
107   26   MAR   74.0
108   27   MAR   59.0
109   28   MAR   73.0
110   29   MAR  131.0
111   30   MAR  129.0
112   31   MAR  109.0

for apr-oct

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

Mounted at /content/drive

In [ ]:
april= pd.read_excel('/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/cpcb_bkc_hourly_2025/AQI_hourly_2025_April_Bandra_Kurla_Complex_Mumbai_MPCB_April_2025.xlsx')

In [ ]:
april.head()

,Date,00:00:00,01:00:00,02:00:00,03:00:00,04:00:00,05:00:00,06:00:00,07:00:00,08:00:00,...,14:00:00,15:00:00,16:00:00,17:00:00,18:00:00,19:00:00,20:00:00,21:00:00,22:00:00,23:00:00
0,1,124.0,122.0,121.0,120.0,120.0,120.0,119.0,118.0,118.0,...,122.0,125.0,128.0,131.0,131.0,132.0,132.0,133.0,133.0,133.0
1,2,133.0,133.0,133.0,135.0,136.0,137.0,138.0,138.0,139.0,...,148.0,144.0,140.0,136.0,134.0,NaN,134.0,128.0,125.0,123.0
2,3,122.0,121.0,120.0,118.0,115.0,NaN,NaN,107.0,106.0,...,87.0,NaN,82.0,80.0,78.0,76.0,NaN,74.0,72.0,70.0
3,4,67.0,64.0,60.0,58.0,56.0,55.0,54.0,51.0,46.0,...,57.0,56.0,55.0,55.0,52.0,46.0,46.0,66.0,NaN,66.0
4,5,73.0,78.0,82.0,88.0,97.0,105.0,111.0,117.0,124.0,...,NaN,142.0,142.0,NaN,NaN,127.0,114.0,102.0,98.0,94.0

In [ ]:
april.isna().sum()

Date        0
00:00:00    4
01:00:00    3
02:00:00    3
03:00:00    4
04:00:00    4
05:00:00    3
06:00:00    3
07:00:00    3
08:00:00    3
09:00:00    3
10:00:00    3
11:00:00    4
12:00:00    3
13:00:00    4
14:00:00    4
15:00:00    4
16:00:00    3
17:00:00    4
18:00:00    5
19:00:00    4
20:00:00    4
21:00:00    3
22:00:00    4
23:00:00    3
dtype: int64

                FUNCTION!!!!!!!!!!!!!!!!!!

In [ ]:
def prep_values(inp_data, month):
  inp_data = inp_data.apply(lambda row: row.ffill(), axis=1)
  inp_data = inp_data.apply(lambda row: row.bfill(), axis=1)
  op_data= pd.DataFrame(columns= ['Day', 'Month', 'AQI'])
  cols= inp_data.columns[1: ]
  len_cols= len(cols)
  op_data['Day']= inp_data['Date']
  op_data['Month']= month

  aqi_values = []
  for i in range(len(inp_data)):
    value= 0
    for j in range(len(cols)):
      value+= inp_data.iloc[i, j+1]
    aqi_values.append(int(value/len_cols))
    op_data['Day'] = op_data['Day'].astype(int)

  op_data['AQI']= aqi_values

  return op_data

In [ ]:
april2= prep_values(april, 'APR')

In [ ]:
april2.head()

   Day Month  AQI
0    1   APR  123
1    2   APR  137
2    3   APR   96
3    4   APR   55
4    5   APR  116

In [ ]:
april2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Day     30 non-null     int64
 1   Month   30 non-null     object
 2   AQI     30 non-null     int64
dtypes: int64(2), object(1)
memory usage: 852.0+ bytes

In [ ]:
print(april2.to_string())

    Day Month  AQI
0     1   APR  123
1     2   APR  137
2     3   APR   96
3     4   APR   55
4     5   APR  116
5     6   APR   60
6     7   APR   53
7     8   APR   61
8     9   APR   63
9    10   APR   85
10   11   APR   71
11   12   APR   70
12   13   APR   80
13   14   APR   87
14   15   APR  101
15   16   APR  107
16   17   APR   89
17   18   APR   80
18   19   APR   69
19   20   APR   84
20   21   APR   85
21   22   APR  110
22   23   APR  132
23   24   APR  117
24   25   APR  103
25   26   APR  110
26   27   APR   27
27   28   APR   28
28   29   APR   81
29   30   APR   90

In [ ]:
may= pd.read_excel('/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/cpcb_bkc_hourly_2025/AQI_hourly_2025_May_Bandra_Kurla_Complex_Mumbai_MPCB_May_2025.xlsx')

june= pd.read_excel('/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/cpcb_bkc_hourly_2025/AQI_hourly_2025_June_Bandra_Kurla_Complex_Mumbai_MPCB_June_2025.xlsx')

july= pd.read_excel('/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/cpcb_bkc_hourly_2025/AQI_hourly_2025_July_Bandra_Kurla_Complex_Mumbai_MPCB_July_2025.xlsx')

august= pd.read_excel('/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/cpcb_bkc_hourly_2025/AQI_hourly_2025_August_Bandra_Kurla_Complex_Mumbai_MPCB_August_2025.xlsx')

september= pd.read_excel('/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/cpcb_bkc_hourly_2025/AQI_hourly_2025_September_Bandra_Kurla_Complex_Mumbai_MPCB_September_2025.xlsx')

october= pd.read_excel('/content/drive/MyDrive/Amajor/img: inp- code- op/cpcb_bkc/cpcb_bkc_hourly_2025/AQI_hourly_2025_October_Bandra_Kurla_Complex_Mumbai_MPCB_October_2025.xlsx')

In [ ]:
may2 = prep_values(may, 'MAY')

june2 = prep_values(june, 'JUN')

july2 = prep_values(july, 'JUL')

august2 = prep_values(august, 'AUG')

september2 = prep_values(september, 'SEP')

october2 = prep_values(october, 'OCT')

In [ ]:
print(may2.info())
print('---------')
print(june2.info())
print('---------')
print(july2.info())
print('---------')
print(august2.info())
print('---------')
print(september2.info())
print('---------')
print(october2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Day     31 non-null     int64
 1   Month   31 non-null     object
 2   AQI     31 non-null     int64
dtypes: int64(2), object(1)
memory usage: 876.0+ bytes
None
---------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Day     30 non-null     int64
 1   Month   30 non-null     object
 2   AQI     30 non-null     int64
dtypes: int64(2), object(1)
memory usage: 852.0+ bytes
None
---------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Day     31 non-null     int64
 1   Month   31 non-null     object
 2   AQI     31 non-null     int64
dtypes: int64(2), object(1)
memory usage: 876.0+ bytes
None
---------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Day     31 non-null     int64
 1   Month   31 non-null     object
 2   AQI     31 non-null     int64
dtypes: int64(2), object(1)
memory usage: 876.0+ bytes
None
---------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Day     30 non-null     int64
 1   Month   30 non-null     object
 2   AQI     30 non-null     int64
dtypes: int64(2), object(1)
memory usage: 852.0+ bytes
None
---------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Day     31 non-null     int64
 1   Month   31 non-null     object
 2   AQI     31 non-null     int64
dtypes: int64(2), object(1)
memory usage: 876.0+ bytes
None

In [ ]:
df2.columns

Index(['Day', 'Month', 'AQI'], dtype='object')

In [ ]:
df3= pd.concat([df2, april2, may2, june2, july2, august2, september2, october2], ignore_index= True)

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Day     304 non-null    int64
 1   Month   304 non-null    object
 2   AQI     304 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 7.3+ KB

In [ ]:
print(df3.to_string())

     Day Month    AQI
0      1   JAN  140.0
1      2   JAN  119.0
2      3   JAN  126.0
3      4   JAN  154.0
4      5   JAN  162.0
5      6   JAN  132.0
6      7   JAN  143.0
7      8   JAN  137.0
8      9   JAN  133.0
9     10   JAN  141.0
10    11   JAN  147.0
11    12   JAN  107.0
12    13   JAN  128.0
13    14   JAN  132.0
14    15   JAN  140.0
15    16   JAN  132.0
16    17   JAN  140.0
17    18   JAN  132.0
18    19   JAN  155.0
19    20   JAN  149.0
20    21   JAN  144.0
21    22   JAN  154.0
22    23   JAN  134.0
23    24   JAN  126.0
24    25   JAN  154.0
25    26   JAN  159.0
26    27   JAN  148.0
27    28   JAN  120.0
28    29   JAN  117.0
29    30   JAN  124.0
30    31   JAN  109.0
31     1   FEB   89.0
32     2   FEB  122.0
33     3   FEB  128.0
34     4   FEB  111.0
35     5   FEB  113.0
36     6   FEB  128.0
37     7   FEB  166.0
38     8   FEB  163.0
39     9   FEB  141.0
40    10   FEB  114.0
41    11   FEB  115.0
42    12   FEB  109.0
43    13   FEB  121.0
44    14   FEB  122.0
45    15   FEB  129.0
46    16   FEB  127.0
47    17   FEB   91.0
48    18   FEB  110.0
49    19   FEB  122.0
50    20   FEB  118.0
51    21   FEB  109.0
52    22   FEB  113.0
53    23   FEB  120.0
54    24   FEB  112.0
55    25   FEB  123.0
56    26   FEB  132.0
57    27   FEB  141.0
58    28   FEB  137.0
59     1   MAR  109.0
60     2   MAR  109.0
61     3   MAR  111.0
62     4   MAR  120.0
63     5   MAR  117.0
64     6   MAR  121.0
65     7   MAR  130.0
66     8   MAR  126.0
67     9   MAR   98.0
68    10   MAR  117.0
69    11   MAR  159.0
70    12   MAR  147.0
71    13   MAR  121.0
72    14   MAR  120.0
73    15   MAR   71.0
74    16   MAR   83.0
75    17   MAR  101.0
76    18   MAR   87.0
77    19   MAR   84.0
78    20   MAR   88.0
79    21   MAR   86.0
80    22   MAR   74.0
81    23   MAR   82.0
82    24   MAR   92.0
83    25   MAR   96.0
84    26   MAR   74.0
85    27   MAR   59.0
86    28   MAR   73.0
87    29   MAR  131.0
88    30   MAR  129.0
89    31   MAR  109.0
90     1   APR  123.0
91     2   APR  137.0
92     3   APR   96.0
93     4   APR   55.0
94     5   APR  116.0
95     6   APR   60.0
96     7   APR   53.0
97     8   APR   61.0
98     9   APR   63.0
99    10   APR   85.0
100   11   APR   71.0
101   12   APR   70.0
102   13   APR   80.0
103   14   APR   87.0
104   15   APR  101.0
105   16   APR  107.0
106   17   APR   89.0
107   18   APR   80.0
108   19   APR   69.0
109   20   APR   84.0
110   21   APR   85.0
111   22   APR  110.0
112   23   APR  132.0
113   24   APR  117.0
114   25   APR  103.0
115   26   APR  110.0
116   27   APR   27.0
117   28   APR   28.0
118   29   APR   81.0
119   30   APR   90.0
120    1   MAY   79.0
121    2   MAY   69.0
122    3   MAY   83.0
123    4   MAY   70.0
124    5   MAY   72.0
125    6   MAY   74.0
126    7   MAY   95.0
127    8   MAY   63.0
128    9   MAY   66.0
129   10   MAY   71.0
130   11   MAY   73.0
131   12   MAY   69.0
132   13   MAY   77.0
133   14   MAY  100.0
134   15   MAY  104.0
135   16   MAY   93.0
136   17   MAY   69.0
137   18   MAY   69.0
138   19   MAY   69.0
139   20   MAY   72.0
140   21   MAY   60.0
141   22   MAY   60.0
142   23   MAY   94.0
143   24   MAY  115.0
144   25   MAY   74.0
145   26   MAY   51.0
146   27   MAY   44.0
147   28   MAY   53.0
148   29   MAY  120.0
149   30   MAY  194.0
150   31   MAY  109.0
151    1   JUN   76.0
152    2   JUN   70.0
153    3   JUN   78.0
154    4   JUN   65.0
155    5   JUN   75.0
156    6   JUN  110.0
157    7   JUN   74.0
158    8   JUN   35.0
159    9   JUN   72.0
160   10   JUN   87.0
161   11   JUN   78.0
162   12   JUN   56.0
163   13   JUN   49.0
164   14   JUN   38.0
165   15   JUN   15.0
166   16   JUN   16.0
167   17   JUN   36.0
168   18   JUN   50.0
169   19   JUN   28.0
170   20   JUN   65.0
171   21   JUN   57.0
172   22   JUN   60.0
173   23   JUN   61.0
174   24   JUN   52.0
175   25   JUN   68.0
176   26   JUN   63.0
177   27   JUN   51.0
178   28   JUN   54.0
179   29   JUN   52.0
180   30   JUN   54.0
181    1   JUL   51.0
182    2   JUL   54.0
183    3   JUL   39.0
184    4   JUL   45.0
185    5   JUL   43.0
186    6   JUL   47.0
187    7   JUL   50.0
188    8   JUL   61.0
189    9   JUL   64.0
190   10   JUL   58.0
191   11   JUL   64.0
192   12   JUL   60.0
193   13   JUL   13.0
194   14   JUL   14.0
195   15   JUL   28.0
196   16   JUL   47.0
197   17   JUL   60.0
198   18   JUL   75.0
199   19   JUL   74.0
200   20   JUL   42.0
201   21   JUL   45.0
202   22   JUL   22.0
203   23   JUL   29.0
204   24   JUL   39.0
205   25   JUL   44.0
206   26   JUL   33.0
207   27   JUL   41.0
208   28   JUL   42.0
209   29   JUL   51.0
210   30   JUL   53.0
211   31   JUL   62.0
212    1   AUG   70.0
213    2   AUG   63.0
214    3   AUG   25.0
215    4   AUG   58.0
216    5   AUG   66.0
217    6   AUG   81.0
218    7   AUG   84.0
219    8   AUG   69.0
220    9   AUG   70.0
221   10   AUG   58.0
222   11   AUG   51.0
223   12   AUG   58.0
224   13   AUG   49.0
225   14   AUG   37.0
226   15   AUG   24.0
227   16   AUG   18.0
228   17   AUG   18.0
229   18   AUG   21.0
230   19   AUG   19.0
231   20   AUG   22.0
232   21   AUG   36.0
233   22   AUG   41.0
234   23   AUG   42.0
235   24   AUG   50.0
236   25   AUG   39.0
237   26   AUG   30.0
238   27   AUG   31.0
239   28   AUG   28.0
240   29   AUG   33.0
241   30   AUG   24.0
242   31   AUG   34.0
243    1   SEP   38.0
244    2   SEP   34.0
245    3   SEP   42.0
246    4   SEP   52.0
247    5   SEP   37.0
248    6   SEP   33.0
249    7   SEP   34.0
250    8   SEP   44.0
251    9   SEP   65.0
252   10   SEP  105.0
253   11   SEP   94.0
254   12   SEP   51.0
255   13   SEP   18.0
256   14   SEP   55.0
257   15   SEP   18.0
258   16   SEP   33.0
259   17   SEP   29.0
260   18   SEP   25.0
261   19   SEP   30.0
262   20   SEP   25.0
263   21   SEP   31.0
264   22   SEP   24.0
265   23   SEP   22.0
266   24   SEP   36.0
267   25   SEP   37.0
268   26   SEP   58.0
269   27   SEP  118.0
270   28   SEP   93.0
271   29   SEP   91.0
272   30   SEP   86.0
273    1   OCT   63.0
274    2   OCT   50.0
275    3   OCT   38.0
276    4   OCT   54.0
277    5   OCT   78.0
278    6   OCT   76.0
279    7   OCT   73.0
280    8   OCT   83.0
281    9   OCT   99.0
282   10   OCT  132.0
283   11   OCT  154.0
284   12   OCT  125.0
285   13   OCT  128.0
286   14   OCT  131.0
287   15   OCT  140.0
288   16   OCT  143.0
289   17   OCT  110.0
290   18   OCT  122.0
291   19   OCT  142.0
292   20   OCT  185.0
293   21   OCT  205.0
294   22   OCT   96.0
295   23   OCT   94.0
296   24   OCT   74.0
297   25   OCT   64.0
298   26   OCT   53.0
299   27   OCT   35.0
300   28   OCT   47.0
301   29   OCT   76.0
302   30   OCT   65.0
303   31   OCT   54.0

In [ ]:
output_path = '/content/drive/MyDrive/Amajor/img_summ/mcpb2025BKC.csv'
df3.to_csv(output_path, index=False)
print(f"DataFrame saved to {output_path}")

DataFrame saved to /content/drive/MyDrive/Amajor/img_summ/mcpb2025BKC.csv

#data consolidation

In [ ]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
csv_2023 = pd.read_csv("/content/drive/MyDrive/Amajor/img_summ/zmcpb_cleaned_data(backup)/mcpb2023BKC.csv")
csv_2024 = pd.read_csv("/content/drive/MyDrive/Amajor/img_summ/zmcpb_cleaned_data(backup)/mcpb2024BKC.csv")
csv_2025 = pd.read_csv("/content/drive/MyDrive/Amajor/img_summ/zmcpb_cleaned_data(backup)/mcpb2025BKC.csv")

csv_2023["Year"] = 2023
csv_2024["Year"] = 2024
csv_2025["Year"] = 2025

df_full = pd.concat([csv_2023, csv_2024, csv_2025], ignore_index=True)

In [ ]:
df_full.head()

   Day Month    AQI  Year
0    1   JAN  147.0  2023
1    2   JAN  188.0  2023
2    3   JAN  214.0  2023
3    4   JAN  204.0  2023
4    5   JAN  223.0  2023

In [ ]:
df_full.tail()

      Day Month   AQI  Year
1031   27   OCT  35.0  2025
1032   28   OCT  47.0  2025
1033   29   OCT  76.0  2025
1034   30   OCT  65.0  2025
1035   31   OCT  54.0  2025

In [ ]:
df_full= df_full[['Year', 'Month', 'Day', 'AQI']]
df_full = df_full.rename(columns={'Day': 'Date'})

In [ ]:
df_full = df_full[~((df_full['Month'] == 'FEB') & (df_full['Date'] == 31))]    #not fn to avoid confusion.

In [ ]:
output_path = '/content/drive/MyDrive/Amajor/img_summ/mcpb_full_BKC.csv'
df_full.to_csv(output_path, index=False)
print(f"DataFrame saved to {output_path}")

DataFrame saved to /content/drive/MyDrive/Amajor/img_summ/mcpb_full_BKC.csv