#v2 -- use this

In [ ]:
import os
import pandas as pd
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
def build_image_index(root_dir):
    records = []
    pattern = re.compile(r"(\d{2})([A-Z]{3})(\d{4})")

    for folder in os.listdir(root_dir):
        folder_path = os.path.join(root_dir, folder)
        if not os.path.isdir(folder_path):
            continue

        for img in os.listdir(folder_path):
            if not img.lower().endswith(".png"):
                continue

            m = pattern.search(img)
            if not m:
                continue

            date = int(m.group(1))
            month = m.group(2)
            year = int(m.group(3))

            records.append({
                "Year": year,
                "Month": month,
                "Date": date,
                "img_path": os.path.join(folder_path, img)
            })

    return pd.DataFrame(records)

In [ ]:
aqi_df= pd.read_csv("/content/drive/MyDrive/Amajor/img_summ/zmcpb_cleaned_data(backup)/mcpb_full_BKC.csv")

In [ ]:
aqi_df.head()

   Year Month  Date    AQI
0  2023   JAN     1  147.0
1  2023   JAN     2  188.0
2  2023   JAN     3  214.0
3  2023   JAN     4  204.0
4  2023   JAN     5  223.0

In [ ]:
print(aqi_df.to_string())

      Year Month  Date    AQI
0     2023   JAN     1  147.0
1     2023   JAN     2  188.0
2     2023   JAN     3  214.0
3     2023   JAN     4  204.0
4     2023   JAN     5  223.0
5     2023   JAN     6  255.0
6     2023   JAN     7  204.0
7     2023   JAN     8  198.0
8     2023   JAN     9  137.0
9     2023   JAN    10  158.0
10    2023   JAN    11  213.0
11    2023   JAN    12  196.0
12    2023   JAN    13  134.0
13    2023   JAN    14  240.0
14    2023   JAN    15  198.0
15    2023   JAN    16  214.0
16    2023   JAN    17  236.0
17    2023   JAN    18  264.0
18    2023   JAN    19  256.0
19    2023   JAN    20  231.0
20    2023   JAN    21  175.0
21    2023   JAN    22  168.0
22    2023   JAN    23  170.0
23    2023   JAN    24  175.0
24    2023   JAN    25  209.0
25    2023   JAN    26  232.0
26    2023   JAN    27  254.0
27    2023   JAN    28  244.0
28    2023   JAN    29  176.0
29    2023   JAN    30  154.0
30    2023   JAN    31  225.0
31    2023   FEB     1  227.0
32    2023   FEB     2  180.0
33    2023   FEB     3  198.0
34    2023   FEB     4  201.0
35    2023   FEB     5  226.0
36    2023   FEB     6  185.0
37    2023   FEB     7  177.0
38    2023   FEB     8  233.0
39    2023   FEB     9  236.0
40    2023   FEB    10  200.0
41    2023   FEB    11  172.0
42    2023   FEB    12  165.0
43    2023   FEB    13  146.0
44    2023   FEB    14  203.0
45    2023   FEB    15  224.0
46    2023   FEB    16  199.0
47    2023   FEB    17  201.0
48    2023   FEB    18  185.0
49    2023   FEB    19  191.0
50    2023   FEB    20  183.0
51    2023   FEB    21  201.0
52    2023   FEB    22  123.0
53    2023   FEB    23  172.0
54    2023   FEB    24  219.0
55    2023   FEB    25  197.0
56    2023   FEB    26  208.0
57    2023   FEB    27  194.0
58    2023   FEB    28  188.0
59    2023   MAR     1  174.0
60    2023   MAR     2  205.0
61    2023   MAR     3  262.0
62    2023   MAR     4  281.0
63    2023   MAR     5  260.0
64    2023   MAR     6  246.0
65    2023   MAR     7  139.0
66    2023   MAR     8  136.0
67    2023   MAR     9  156.0
68    2023   MAR    10  145.0
69    2023   MAR    11  163.0
70    2023   MAR    12  186.0
71    2023   MAR    13  213.0
72    2023   MAR    14  199.0
73    2023   MAR    15  165.0
74    2023   MAR    16  146.0
75    2023   MAR    17  117.0
76    2023   MAR    18  118.0
77    2023   MAR    19   97.0
78    2023   MAR    20   90.0
79    2023   MAR    21   91.0
80    2023   MAR    22   96.0
81    2023   MAR    23   86.0
82    2023   MAR    24   73.0
83    2023   MAR    25   88.0
84    2023   MAR    26   98.0
85    2023   MAR    27   97.0
86    2023   MAR    28  117.0
87    2023   MAR    29  125.0
88    2023   MAR    30  106.0
89    2023   MAR    31   82.0
90    2023   APR     1  108.0
91    2023   APR     2   93.0
92    2023   APR     3   86.0
93    2023   APR     4   86.0
94    2023   APR     5   87.0
95    2023   APR     6   99.0
96    2023   APR     7  149.0
97    2023   APR     8  182.0
98    2023   APR     9  156.0
99    2023   APR    10  132.0
100   2023   APR    11  112.0
101   2023   APR    12  134.0
102   2023   APR    13  130.0
103   2023   APR    14  126.0
104   2023   APR    15  110.0
105   2023   APR    16  100.0
106   2023   APR    17   95.0
107   2023   APR    18  103.0
108   2023   APR    19  125.0
109   2023   APR    20  106.0
110   2023   APR    21   79.0
111   2023   APR    22   74.0
112   2023   APR    23   86.0
113   2023   APR    24   77.0
114   2023   APR    25  101.0
115   2023   APR    26   94.0
116   2023   APR    27   92.0
117   2023   APR    28   71.0
118   2023   APR    29   81.0
119   2023   APR    30   81.0
120   2023   MAY     1   74.0
121   2023   MAY     2   78.0
122   2023   MAY     3   80.0
123   2023   MAY     4   76.0
124   2023   MAY     5   75.0
125   2023   MAY     6   74.0
126   2023   MAY     7   84.0
127   2023   MAY     8   82.0
128   2023   MAY     9   91.0
129   2023   MAY    10  112.0
130   2023   MAY    11  121.0
131   2023   MAY    12  120.0
132   2023   MAY    13   99.0
133   2023   MAY    14   52.0
134   2023   MAY    15   68.0
135   2023   MAY    16   67.0
136   2023   MAY    17   69.0
137   2023   MAY    18   75.0
138   2023   MAY    19   76.0
139   2023   MAY    20   80.0
140   2023   MAY    21   73.0
141   2023   MAY    22   70.0
142   2023   MAY    23   79.0
143   2023   MAY    24   69.0
144   2023   MAY    25   68.0
145   2023   MAY    26   67.0
146   2023   MAY    27   73.0
147   2023   MAY    28   75.0
148   2023   MAY    29   78.0
149   2023   MAY    30   80.0
150   2023   MAY    31   97.0
151   2023   JUN     1   89.0
152   2023   JUN     2   84.0
153   2023   JUN     3   74.0
154   2023   JUN     4   72.0
155   2023   JUN     5   73.0
156   2023   JUN     6   81.0
157   2023   JUN     7   87.0
158   2023   JUN     8   89.0
159   2023   JUN     9   81.0
160   2023   JUN    10   85.0
161   2023   JUN    11   85.0
162   2023   JUN    12   90.0
163   2023   JUN    13   83.0
164   2023   JUN    14   78.0
165   2023   JUN    15   83.0
166   2023   JUN    16   84.0
167   2023   JUN    17   89.0
168   2023   JUN    18   98.0
169   2023   JUN    19   92.0
170   2023   JUN    20   93.0
171   2023   JUN    21  100.0
172   2023   JUN    22   97.0
173   2023   JUN    23   77.0
174   2023   JUN    24   73.0
175   2023   JUN    25   61.0
176   2023   JUN    26   73.0
177   2023   JUN    27   58.0
178   2023   JUN    28   61.0
179   2023   JUN    29   53.0
180   2023   JUN    30   56.0
181   2023   JUL     1   67.0
182   2023   JUL     2   54.0
183   2023   JUL     3   62.0
184   2023   JUL     4   65.0
185   2023   JUL     5   65.0
186   2023   JUL     6   51.0
187   2023   JUL     7   54.0
188   2023   JUL     8   91.0
189   2023   JUL     9   70.0
190   2023   JUL    10   65.0
191   2023   JUL    11   73.0
192   2023   JUL    12   77.0
193   2023   JUL    13  108.0
194   2023   JUL    14   87.0
195   2023   JUL    15   82.0
196   2023   JUL    16   87.0
197   2023   JUL    17   83.0
198   2023   JUL    18   80.0
199   2023   JUL    19   86.0
200   2023   JUL    20   86.0
201   2023   JUL    21   87.0
202   2023   JUL    22   88.0
203   2023   JUL    23   88.0
204   2023   JUL    24   87.0
205   2023   JUL    25   81.0
206   2023   JUL    26   48.0
207   2023   JUL    27   45.0
208   2023   JUL    28   49.0
209   2023   JUL    29   51.0
210   2023   JUL    30   52.0
211   2023   JUL    31   53.0
212   2023   AUG     1   54.0
213   2023   AUG     2   58.0
214   2023   AUG     3   62.0
215   2023   AUG     4   73.0
216   2023   AUG     5   62.0
217   2023   AUG     6   68.0
218   2023   AUG     7   70.0
219   2023   AUG     8   71.0
220   2023   AUG     9   78.0
221   2023   AUG    10   65.0
222   2023   AUG    11   61.0
223   2023   AUG    12   65.0
224   2023   AUG    13   68.0
225   2023   AUG    14   67.0
226   2023   AUG    15   62.0
227   2023   AUG    16   56.0
228   2023   AUG    17   55.0
229   2023   AUG    18   55.0
230   2023   AUG    19   50.0
231   2023   AUG    20   53.0
232   2023   AUG    21   51.0
233   2023   AUG    22   50.0
234   2023   AUG    23   52.0
235   2023   AUG    24   53.0
236   2023   AUG    25   54.0
237   2023   AUG    26   61.0
238   2023   AUG    27   60.0
239   2023   AUG    28   56.0
240   2023   AUG    29   64.0
241   2023   AUG    30   87.0
242   2023   AUG    31   91.0
243   2023   SEP     1   84.0
244   2023   SEP     2   81.0
245   2023   SEP     3   80.0
246   2023   SEP     4   86.0
247   2023   SEP     5   81.0
248   2023   SEP     6   78.0
249   2023   SEP     7   71.0
250   2023   SEP     8   65.0
251   2023   SEP     9   61.0
252   2023   SEP    10   54.0
253   2023   SEP    11   54.0
254   2023   SEP    12   59.0
255   2023   SEP    13   58.0
256   2023   SEP    14   63.0
257   2023   SEP    15   65.0
258   2023   SEP    16   60.0
259   2023   SEP    17   57.0
260   2023   SEP    18   58.0
261   2023   SEP    19   53.0
262   2023   SEP    20   51.0
263   2023   SEP    21   59.0
264   2023   SEP    22   59.0
265   2023   SEP    23   58.0
266   2023   SEP    24   53.0
267   2023   SEP    25   59.0
268   2023   SEP    26   67.0
269   2023   SEP    27   68.0
270   2023   SEP    28   77.0
271   2023   SEP    29   94.0
272   2023   SEP    30   72.0
273   2023   OCT     1   87.0
274   2023   OCT     2   97.0
275   2023   OCT     3  116.0
276   2023   OCT     4  121.0
277   2023   OCT     5  120.0
278   2023   OCT     6  131.0
279   2023   OCT     7  120.0
280   2023   OCT     8  110.0
281   2023   OCT     9  144.0
282   2023   OCT    10  109.0
283   2023   OCT    11   88.0
284   2023   OCT    12  100.0
285   2023   OCT    13  159.0
286   2023   OCT    14  177.0
287   2023   OCT    15  150.0
288   2023   OCT    16  185.0
289   2023   OCT    17  189.0
290   2023   OCT    18  199.0
291   2023   OCT    19  156.0
292   2023   OCT    20  185.0
293   2023   OCT    21  155.0
294   2023   OCT    22  172.0
295   2023   OCT    23  177.0
296   2023   OCT    24  182.0
297   2023   OCT    25  157.0
298   2023   OCT    26  157.0
299   2023   OCT    27  139.0
300   2023   OCT    28  153.0
301   2023   OCT    29  152.0
302   2023   OCT    30  157.0
303   2023   OCT    31  168.0
304   2023   NOV     1  175.0
305   2023   NOV     2  169.0
306   2023   NOV     3  178.0
307   2023   NOV     4  180.0
308   2023   NOV     5  198.0
309   2023   NOV     6  198.0
310   2023   NOV     7  186.0
311   2023   NOV     8  131.0
312   2023   NOV     9  111.0
313   2023   NOV    10   87.0
314   2023   NOV    11   90.0
315   2023   NOV    12  154.0
316   2023   NOV    13  193.0
317   2023   NOV    14  168.0
318   2023   NOV    15  201.0
319   2023   NOV    16  168.0
320   2023   NOV    17  140.0
321   2023   NOV    18  162.0
322   2023   NOV    19  159.0
323   2023   NOV    20  115.0
324   2023   NOV    21  132.0
325   2023   NOV    22  123.0
326   2023   NOV    23  137.0
327   2023   NOV    24  152.0
328   2023   NOV    25  124.0
329   2023   NOV    26   98.0
330   2023   NOV    27   59.0
331   2023   NOV    28   61.0
332   2023   NOV    29   94.0
333   2023   NOV    30  102.0
334   2023   DEC     1  127.0
335   2023   DEC     2  138.0
336   2023   DEC     3  144.0
337   2023   DEC     4  128.0
338   2023   DEC     5  136.0
339   2023   DEC     6  154.0
340   2023   DEC     7  125.0
341   2023   DEC     8  117.0
342   2023   DEC     9  114.0
343   2023   DEC    10  114.0
344   2023   DEC    11  108.0
345   2023   DEC    12  114.0
346   2023   DEC    13  115.0
347   2023   DEC    14  134.0
348   2023   DEC    15  139.0
349   2023   DEC    16  133.0
350   2023   DEC    17  126.0
351   2023   DEC    18  136.0
352   2023   DEC    19  138.0
353   2023   DEC    20  134.0
354   2023   DEC    21  157.0
355   2023   DEC    22  189.0
356   2023   DEC    23  190.0
357   2023   DEC    24  166.0
358   2023   DEC    25  155.0
359   2023   DEC    26  178.0
360   2023   DEC    27  174.0
361   2023   DEC    28  194.0
362   2023   DEC    29  181.0
363   2023   DEC    30  161.0
364   2023   DEC    31  143.0
365   2024   JAN     1  151.0
366   2024   JAN     2  151.0
367   2024   JAN     3  136.0
368   2024   JAN     4  154.0
369   2024   JAN     5  180.0
370   2024   JAN     6  205.0
371   2024   JAN     7  162.0
372   2024   JAN     8  105.0
373   2024   JAN     9  106.0
374   2024   JAN    10   79.0
375   2024   JAN    11  149.0
376   2024   JAN    12  171.0
377   2024   JAN    13  156.0
378   2024   JAN    14  134.0
379   2024   JAN    15  100.0
380   2024   JAN    16  108.0
381   2024   JAN    17  172.0
382   2024   JAN    18  156.0
383   2024   JAN    19  116.0
384   2024   JAN    20  226.0
385   2024   JAN    21  132.0
386   2024   JAN    22  132.0
387   2024   JAN    23  135.0
388   2024   JAN    24  138.0
389   2024   JAN    25  108.0
390   2024   JAN    26  150.0
391   2024   JAN    27   99.0
392   2024   JAN    28  171.0
393   2024   JAN    29  123.0
394   2024   JAN    30  144.0
395   2024   JAN    31  122.0
396   2024   FEB     1  106.0
397   2024   FEB     2   99.0
398   2024   FEB     3  165.0
399   2024   FEB     4  244.0
400   2024   FEB     5  239.0
401   2024   FEB     6  146.0
402   2024   FEB     7  134.0
403   2024   FEB     8  153.0
404   2024   FEB     9  158.0
405   2024   FEB    10  150.0
406   2024   FEB    11  158.0
407   2024   FEB    12  141.0
408   2024   FEB    13  167.0
409   2024   FEB    14  143.0
410   2024   FEB    15  205.0
411   2024   FEB    16  205.0
412   2024   FEB    17  205.0
413   2024   FEB    18  187.0
414   2024   FEB    19  131.0
415   2024   FEB    20  151.0
416   2024   FEB    21   83.0
417   2024   FEB    22  104.0
418   2024   FEB    23  127.0
419   2024   FEB    24  173.0
420   2024   FEB    25  211.0
421   2024   FEB    26  204.0
422   2024   FEB    27  198.0
423   2024   FEB    28  180.0
424   2024   MAR     1  130.0
425   2024   MAR     2   88.0
426   2024   MAR     3   51.0
427   2024   MAR     4   61.0
428   2024   MAR     5  147.0
429   2024   MAR     6  165.0
430   2024   MAR     7  131.0
431   2024   MAR     8  170.0
432   2024   MAR     9  166.0
433   2024   MAR    10  137.0
434   2024   MAR    11  110.0
435   2024   MAR    12  130.0
436   2024   MAR    13   90.0
437   2024   MAR    14   82.0
438   2024   MAR    15  129.0
439   2024   MAR    16  165.0
440   2024   MAR    17  135.0
441   2024   MAR    18  126.0
442   2024   MAR    19  148.0
443   2024   MAR    20  162.0
444   2024   MAR    21  163.0
445   2024   MAR    22  186.0
446   2024   MAR    23  129.0
447   2024   MAR    24  101.0
448   2024   MAR    25   92.0
449   2024   MAR    26   88.0
450   2024   MAR    27  102.0
451   2024   MAR    28  102.0
452   2024   MAR    29  116.0
453   2024   MAR    30  118.0
454   2024   MAR    31  114.0
455   2024   APR     1  113.0
456   2024   APR     2  205.0
457   2024   APR     3  153.0
458   2024   APR     4  100.0
459   2024   APR     5   90.0
460   2024   APR     6  124.0
461   2024   APR     7  124.0
462   2024   APR     8  124.0
463   2024   APR     9  124.0
464   2024   APR    10  124.0
465   2024   APR    11   97.0
466   2024   APR    12   88.0
467   2024   APR    13   86.0
468   2024   APR    14   91.0
469   2024   APR    15   85.0
470   2024   APR    16  158.0
471   2024   APR    17  129.0
472   2024   APR    18  106.0
473   2024   APR    19  102.0
474   2024   APR    20  102.0
475   2024   APR    21  110.0
476   2024   APR    22   64.0
477   2024   APR    23   96.0
478   2024   APR    24   96.0
479   2024   APR    25   92.0
480   2024   APR    26   74.0
481   2024   APR    27   94.0
482   2024   APR    28  245.0
483   2024   APR    29  114.0
484   2024   APR    30  123.0
485   2024   MAY     1  108.0
486   2024   MAY     2   98.0
487   2024   MAY     3  135.0
488   2024   MAY     4   95.0
489   2024   MAY     5   82.0
490   2024   MAY     6   66.0
491   2024   MAY     7   67.0
492   2024   MAY     8   82.0
493   2024   MAY     9   71.0
494   2024   MAY    10   69.0
495   2024   MAY    11   85.0
496   2024   MAY    12   81.0
497   2024   MAY    13   73.0
498   2024   MAY    14  183.0
499   2024   MAY    15  177.0
500   2024   MAY    16  105.0
501   2024   MAY    17  131.0
502   2024   MAY    18  100.0
503   2024   MAY    19   97.0
504   2024   MAY    20   74.0
505   2024   MAY    21   77.0
506   2024   MAY    22   88.0
507   2024   MAY    23   88.0
508   2024   MAY    24   88.0
509   2024   MAY    25   86.0
510   2024   MAY    26   86.0
511   2024   MAY    27   79.0
512   2024   MAY    28   85.0
513   2024   MAY    29  106.0
514   2024   MAY    30  108.0
515   2024   MAY    31   89.0
516   2024   JUN     1   78.0
517   2024   JUN     2   83.0
518   2024   JUN     3   76.0
519   2024   JUN     4  109.0
520   2024   JUN     5   81.0
521   2024   JUN     6   62.0
522   2024   JUN     7   85.0
523   2024   JUN     8   90.0
524   2024   JUN     9   67.0
525   2024   JUN    10   53.0
526   2024   JUN    11   50.0
527   2024   JUN    12   84.0
528   2024   JUN    13   80.0
529   2024   JUN    14   62.0
530   2024   JUN    15   76.0
531   2024   JUN    16   72.0
532   2024   JUN    17   77.0
533   2024   JUN    18   77.0
534   2024   JUN    19   49.0
535   2024   JUN    20   57.0
536   2024   JUN    21   65.0
537   2024   JUN    22   75.0
538   2024   JUN    23   84.0
539   2024   JUN    24   57.0
540   2024   JUN    25   79.0
541   2024   JUN    26   59.0
542   2024   JUN    27   38.0
543   2024   JUN    28   38.0
544   2024   JUN    29   38.0
545   2024   JUN    30   53.0
546   2024   JUL     1   62.0
547   2024   JUL     2   56.0
548   2024   JUL     3   92.0
549   2024   JUL     4   88.0
550   2024   JUL     5   70.0
551   2024   JUL     6   59.0
552   2024   JUL     7   59.0
553   2024   JUL     8   59.0
554   2024   JUL     9   54.0
555   2024   JUL    10   48.0
556   2024   JUL    11   46.0
557   2024   JUL    12   54.0
558   2024   JUL    13   42.0
559   2024   JUL    14   35.0
560   2024   JUL    15   58.0
561   2024   JUL    16   38.0
562   2024   JUL    17   48.0
563   2024   JUL    18   41.0
564   2024   JUL    19   39.0
565   2024   JUL    20   37.0
566   2024   JUL    21   31.0
567   2024   JUL    22   43.0
568   2024   JUL    23   38.0
569   2024   JUL    24   38.0
570   2024   JUL    25   41.0
571   2024   JUL    26   41.0
572   2024   JUL    27   50.0
573   2024   JUL    28   56.0
574   2024   JUL    29   56.0
575   2024   JUL    30   50.0
576   2024   JUL    31   58.0
577   2024   AUG     1   50.0
578   2024   AUG     2   41.0
579   2024   AUG     3   33.0
580   2024   AUG     4   32.0
581   2024   AUG     5   41.0
582   2024   AUG     6   42.0
583   2024   AUG     7   40.0
584   2024   AUG     8   58.0
585   2024   AUG     9   59.0
586   2024   AUG    10   52.0
587   2024   AUG    11   40.0
588   2024   AUG    12   54.0
589   2024   AUG    13   66.0
590   2024   AUG    14   88.0
591   2024   AUG    15  102.0
592   2024   AUG    16   61.0
593   2024   AUG    17   84.0
594   2024   AUG    18   97.0
595   2024   AUG    19   69.0
596   2024   AUG    20   76.0
597   2024   AUG    21   93.0
598   2024   AUG    22   60.0
599   2024   AUG    23   61.0
600   2024   AUG    24   48.0
601   2024   AUG    25   44.0
602   2024   AUG    26   44.0
603   2024   AUG    27   46.0
604   2024   AUG    28   46.0
605   2024   AUG    29   62.0
606   2024   AUG    30   62.0
607   2024   AUG    31   95.0
608   2024   SEP     1   60.0
609   2024   SEP     2   65.0
610   2024   SEP     3   48.0
611   2024   SEP     4   59.0
612   2024   SEP     5   40.0
613   2024   SEP     6   45.0
614   2024   SEP     7   43.0
615   2024   SEP     8   43.0
616   2024   SEP     9   53.0
617   2024   SEP    10   78.0
618   2024   SEP    11   78.0
619   2024   SEP    12   66.0
620   2024   SEP    13   66.0
621   2024   SEP    14   81.0
622   2024   SEP    15   91.0
623   2024   SEP    16  103.0
624   2024   SEP    17  121.0
625   2024   SEP    18   86.0
626   2024   SEP    19  116.0
627   2024   SEP    20  169.0
628   2024   SEP    21  135.0
629   2024   SEP    22  114.0
630   2024   SEP    23   80.0
631   2024   SEP    24   50.0
632   2024   SEP    25   50.0
633   2024   SEP    26   58.0
634   2024   SEP    27   49.0
635   2024   SEP    28   54.0
636   2024   SEP    29   51.0
637   2024   SEP    30   58.0
638   2024   OCT     1   79.0
639   2024   OCT     2  110.0
640   2024   OCT     3   64.0
641   2024   OCT     4   47.0
642   2024   OCT     5   98.0
643   2024   OCT     6  118.0
644   2024   OCT     7  115.0
645   2024   OCT     8  231.0
646   2024   OCT     9  231.0
647   2024   OCT    10  231.0
648   2024   OCT    11   78.0
649   2024   OCT    12   56.0
650   2024   OCT    13   56.0
651   2024   OCT    14   56.0
652   2024   OCT    15  117.0
653   2024   OCT    16  127.0
654   2024   OCT    17  127.0
655   2024   OCT    18  156.0
656   2024   OCT    19   65.0
657   2024   OCT    20   67.0
658   2024   OCT    21   67.0
659   2024   OCT    22  100.0
660   2024   OCT    23  109.0
661   2024   OCT    24  134.0
662   2024   OCT    25  165.0
663   2024   OCT    26  168.0
664   2024   OCT    27  146.0

In [ ]:
img_df = build_image_index("/content/drive/MyDrive/Amajor/img_summ/op_for_summ")

In [ ]:
img_df.head()

   Year Month  Date                                           img_path
0  2023   JAN     1  /content/drive/MyDrive/Amajor/img_summ/op_for_...
1  2023   JAN     2  /content/drive/MyDrive/Amajor/img_summ/op_for_...
2  2023   JAN     3  /content/drive/MyDrive/Amajor/img_summ/op_for_...
3  2023   JAN     4  /content/drive/MyDrive/Amajor/img_summ/op_for_...
4  2023   JAN     5  /content/drive/MyDrive/Amajor/img_summ/op_for_...

In [ ]:
print(img_df.to_string())

      Year Month  Date                                                                     img_path
0     2023   JAN     1  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/01JAN2023.png
1     2023   JAN     2  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/02JAN2023.png
2     2023   JAN     3  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/03JAN2023.png
3     2023   JAN     4  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/04JAN2023.png
4     2023   JAN     5  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/05JAN2023.png
5     2023   JAN     6  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/06JAN2023.png
6     2023   JAN     7  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/07JAN2023.png
7     2023   JAN     8  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/08JAN2023.png
8     2023   JAN     9  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/09JAN2023.png
9     2023   JAN    10  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/10JAN2023.png
10    2023   JAN    11  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/11JAN2023.png
11    2023   JAN    12  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/12JAN2023.png
12    2023   JAN    13  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/13JAN2023.png
13    2023   JAN    14  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/14JAN2023.png
14    2023   JAN    15  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/15JAN2023.png
15    2023   JAN    16  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/16JAN2023.png
16    2023   JAN    17  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/17JAN2023.png
17    2023   JAN    18  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/18JAN2023.png
18    2023   JAN    19  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/19JAN2023.png
19    2023   JAN    20  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/20JAN2023.png
20    2023   JAN    21  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/21JAN2023.png
21    2023   JAN    22  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/22JAN2023.png
22    2023   JAN    23  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/23JAN2023.png
23    2023   JAN    24  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/24JAN2023.png
24    2023   JAN    25  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/25JAN2023.png
25    2023   JAN    26  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/26JAN2023.png
26    2023   JAN    27  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/27JAN2023.png
27    2023   JAN    28  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/28JAN2023.png
28    2023   JAN    29  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/29JAN2023.png
29    2023   JAN    30  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/30JAN2023.png
30    2023   JAN    31  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/31JAN2023.png
31    2023   FEB     1  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/01FEB2023.png
32    2023   FEB     2  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/02FEB2023.png
33    2023   FEB     3  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/03FEB2023.png
34    2023   FEB     4  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/04FEB2023.png
35    2023   FEB     5  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/05FEB2023.png
36    2023   FEB     6  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/06FEB2023.png
37    2023   FEB     7  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/07FEB2023.png
38    2023   FEB     8  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/08FEB2023.png
39    2023   FEB     9  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/09FEB2023.png
40    2023   FEB    10  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/10FEB2023.png
41    2023   FEB    11  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/11FEB2023.png
42    2023   FEB    12  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/12FEB2023.png
43    2023   FEB    13  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/13FEB2023.png
44    2023   FEB    14  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/14FEB2023.png
45    2023   FEB    15  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/15FEB2023.png
46    2023   FEB    16  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/16FEB2023.png
47    2023   FEB    17  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/17FEB2023.png
48    2023   FEB    18  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/18FEB2023.png
49    2023   FEB    19  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/19FEB2023.png
50    2023   FEB    20  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/20FEB2023.png
51    2023   FEB    21  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/21FEB2023.png
52    2023   FEB    22  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/22FEB2023.png
53    2023   FEB    23  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/23FEB2023.png
54    2023   FEB    24  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/24FEB2023.png
55    2023   FEB    25  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/25FEB2023.png
56    2023   FEB    26  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/26FEB2023.png
57    2023   FEB    27  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/27FEB2023.png
58    2023   FEB    28  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/28FEB2023.png
59    2023   MAR     1  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/01MAR2023.png
60    2023   MAR     2  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/02MAR2023.png
61    2023   MAR     3  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/03MAR2023.png
62    2023   MAR     4  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/04MAR2023.png
63    2023   MAR     5  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/05MAR2023.png
64    2023   MAR     6  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/06MAR2023.png
65    2023   MAR     7  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/07MAR2023.png
66    2023   MAR     8  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/08MAR2023.png
67    2023   MAR     9  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/09MAR2023.png
68    2023   MAR    10  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/10MAR2023.png
69    2023   MAR    11  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/11MAR2023.png
70    2023   MAR    12  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/12MAR2023.png
71    2023   MAR    13  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/13MAR2023.png
72    2023   MAR    14  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/14MAR2023.png
73    2023   MAR    15  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/15MAR2023.png
74    2023   MAR    16  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/16MAR2023.png
75    2023   MAR    17  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/17MAR2023.png
76    2023   MAR    18  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/18MAR2023.png
77    2023   MAR    19  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/19MAR2023.png
78    2023   MAR    20  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/20MAR2023.png
79    2023   MAR    21  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/21MAR2023.png
80    2023   MAR    22  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/22MAR2023.png
81    2023   MAR    23  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/23MAR2023.png
82    2023   MAR    24  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/24MAR2023.png
83    2023   MAR    25  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/25MAR2023.png
84    2023   MAR    26  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/26MAR2023.png
85    2023   MAR    27  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/27MAR2023.png
86    2023   MAR    28  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/28MAR2023.png
87    2023   MAR    29  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/29MAR2023.png
88    2023   MAR    30  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/30MAR2023.png
89    2023   MAR    31  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/31MAR2023.png
90    2023   APR     1  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/01APR2023.png
91    2023   APR     2  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/02APR2023.png
92    2023   APR     3  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/03APR2023.png
93    2023   APR     4  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/04APR2023.png
94    2023   APR     5  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/05APR2023.png
95    2023   APR     6  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/06APR2023.png
96    2023   APR     7  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/07APR2023.png
97    2023   APR     8  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/08APR2023.png
98    2023   APR     9  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/09APR2023.png
99    2023   APR    10  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/10APR2023.png
100   2023   APR    11  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/11APR2023.png
101   2023   APR    12  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/12APR2023.png
102   2023   APR    13  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/13APR2023.png
103   2023   APR    14  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/14APR2023.png
104   2023   APR    15  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/15APR2023.png
105   2023   APR    16  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/16APR2023.png
106   2023   APR    17  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/17APR2023.png
107   2023   APR    18  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/18APR2023.png
108   2023   APR    19  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/19APR2023.png
109   2023   APR    20  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/20APR2023.png
110   2023   APR    21  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/21APR2023.png
111   2023   APR    22  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/22APR2023.png
112   2023   APR    23  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/23APR2023.png
113   2023   APR    24  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/24APR2023.png
114   2023   APR    25  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/25APR2023.png
115   2023   APR    26  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/26APR2023.png
116   2023   APR    27  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/27APR2023.png
117   2023   APR    28  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/28APR2023.png
118   2023   APR    29  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/29APR2023.png
119   2023   APR    30  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/30APR2023.png
120   2023   MAY     1  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/01MAY2023.png
121   2023   MAY     2  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/02MAY2023.png
122   2023   MAY     3  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/03MAY2023.png
123   2023   MAY     4  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/04MAY2023.png
124   2023   MAY     5  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/05MAY2023.png
125   2023   MAY     6  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/06MAY2023.png
126   2023   MAY     7  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/07MAY2023.png
127   2023   MAY     8  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/08MAY2023.png
128   2023   MAY    15  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/15MAY2023.png
129   2023   MAY    16  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/16MAY2023.png
130   2023   MAY    17  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/17MAY2023.png
131   2023   MAY    18  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/18MAY2023.png
132   2023   MAY    19  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/19MAY2023.png
133   2023   MAY    20  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/20MAY2023.png
134   2023   MAY    21  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/21MAY2023.png
135   2023   MAY    22  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/22MAY2023.png
136   2023   MAY    23  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/23MAY2023.png
137   2023   MAY    24  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/24MAY2023.png
138   2023   MAY    25  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/25MAY2023.png
139   2023   MAY    26  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/26MAY2023.png
140   2023   MAY    27  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/27MAY2023.png
141   2023   MAY    28  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/28MAY2023.png
142   2023   MAY    29  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/29MAY2023.png
143   2023   MAY    30  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/30MAY2023.png
144   2023   MAY    31  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/31MAY2023.png
145   2023   JUN     1  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/01JUN2023.png
146   2023   JUN     2  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/02JUN2023.png
147   2023   JUN     3  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/03JUN2023.png
148   2023   JUN     4  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/04JUN2023.png
149   2023   JUN     5  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/05JUN2023.png
150   2023   JUN     6  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/06JUN2023.png
151   2023   JUN    16  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/16JUN2023.png
152   2023   JUN    17  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/17JUN2023.png
153   2023   JUN    18  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/18JUN2023.png
154   2023   JUN    19  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/19JUN2023.png
155   2023   JUN    20  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/20JUN2023.png
156   2023   JUN    21  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/21JUN2023.png
157   2023   JUN    22  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/22JUN2023.png
158   2023   JUN    23  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/23JUN2023.png
159   2023   JUN    24  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/24JUN2023.png
160   2023   JUN    25  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/25JUN2023.png
161   2023   JUN    26  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/26JUN2023.png
162   2023   JUN    27  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/27JUN2023.png
163   2023   JUN    28  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/28JUN2023.png
164   2023   JUN    29  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/29JUN2023.png
165   2023   JUN    30  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/30JUN2023.png
166   2023   JUL     1  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/01JUL2023.png
167   2023   JUL     2  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/02JUL2023.png
168   2023   JUL     3  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/03JUL2023.png
169   2023   JUL     4  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/04JUL2023.png
170   2023   JUL     5  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/05JUL2023.png
171   2023   JUL     6  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/06JUL2023.png
172   2023   JUL     7  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/07JUL2023.png
173   2023   JUL     8  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/08JUL2023.png
174   2023   JUL     9  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/09JUL2023.png
175   2023   JUL    10  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/10JUL2023.png
176   2023   JUL    11  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/11JUL2023.png
177   2023   JUL    12  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/12JUL2023.png
178   2023   JUL    13  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/13JUL2023.png
179   2023   JUL    14  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/14JUL2023.png
180   2023   JUL    15  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/15JUL2023.png
181   2023   JUL    16  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/16JUL2023.png
182   2023   JUL    17  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/17JUL2023.png
183   2023   JUL    18  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/18JUL2023.png
184   2023   JUL    19  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/19JUL2023.png
185   2023   JUL    20  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/20JUL2023.png
186   2023   JUL    21  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/21JUL2023.png
187   2023   JUL    22  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/22JUL2023.png
188   2023   JUL    23  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/23JUL2023.png
189   2023   JUL    24  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/24JUL2023.png
190   2023   JUL    25  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/25JUL2023.png
191   2023   JUL    26  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/26JUL2023.png
192   2023   JUL    27  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/27JUL2023.png
193   2023   JUL    28  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/28JUL2023.png
194   2023   JUL    29  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/29JUL2023.png
195   2023   JUL    30  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/30JUL2023.png
196   2023   JUL    31  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/31JUL2023.png
197   2023   AUG     1  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 08_summ/01AUG2023.png
198   2023   AUG     2  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 08_summ/02AUG2023.png

In [ ]:
df_full = aqi_df.merge(
    img_df,
    on=["Year", "Month", "Date"],
    how="left"
)

In [ ]:
df_full.isna().sum()    #yes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Year         0
Month        0
Date         0
AQI          0
img_path    28
dtype: int64

In [ ]:
print(df_full.to_string())

      Year Month  Date    AQI                                                                     img_path
0     2023   JAN     1  147.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/01JAN2023.png
1     2023   JAN     2  188.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/02JAN2023.png
2     2023   JAN     3  214.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/03JAN2023.png
3     2023   JAN     4  204.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/04JAN2023.png
4     2023   JAN     5  223.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/05JAN2023.png
5     2023   JAN     6  255.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/06JAN2023.png
6     2023   JAN     7  204.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/07JAN2023.png
7     2023   JAN     8  198.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/08JAN2023.png
8     2023   JAN     9  137.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/09JAN2023.png
9     2023   JAN    10  158.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/10JAN2023.png
10    2023   JAN    11  213.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/11JAN2023.png
11    2023   JAN    12  196.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/12JAN2023.png
12    2023   JAN    13  134.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/13JAN2023.png
13    2023   JAN    14  240.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/14JAN2023.png
14    2023   JAN    15  198.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/15JAN2023.png
15    2023   JAN    16  214.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/16JAN2023.png
16    2023   JAN    17  236.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/17JAN2023.png
17    2023   JAN    18  264.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/18JAN2023.png
18    2023   JAN    19  256.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/19JAN2023.png
19    2023   JAN    20  231.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/20JAN2023.png
20    2023   JAN    21  175.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/21JAN2023.png
21    2023   JAN    22  168.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/22JAN2023.png
22    2023   JAN    23  170.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/23JAN2023.png
23    2023   JAN    24  175.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/24JAN2023.png
24    2023   JAN    25  209.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/25JAN2023.png
25    2023   JAN    26  232.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/26JAN2023.png
26    2023   JAN    27  254.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/27JAN2023.png
27    2023   JAN    28  244.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/28JAN2023.png
28    2023   JAN    29  176.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/29JAN2023.png
29    2023   JAN    30  154.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/30JAN2023.png
30    2023   JAN    31  225.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 01_summ/31JAN2023.png
31    2023   FEB     1  227.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/01FEB2023.png
32    2023   FEB     2  180.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/02FEB2023.png
33    2023   FEB     3  198.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/03FEB2023.png
34    2023   FEB     4  201.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/04FEB2023.png
35    2023   FEB     5  226.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/05FEB2023.png
36    2023   FEB     6  185.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/06FEB2023.png
37    2023   FEB     7  177.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/07FEB2023.png
38    2023   FEB     8  233.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/08FEB2023.png
39    2023   FEB     9  236.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/09FEB2023.png
40    2023   FEB    10  200.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/10FEB2023.png
41    2023   FEB    11  172.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/11FEB2023.png
42    2023   FEB    12  165.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/12FEB2023.png
43    2023   FEB    13  146.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/13FEB2023.png
44    2023   FEB    14  203.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/14FEB2023.png
45    2023   FEB    15  224.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/15FEB2023.png
46    2023   FEB    16  199.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/16FEB2023.png
47    2023   FEB    17  201.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/17FEB2023.png
48    2023   FEB    18  185.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/18FEB2023.png
49    2023   FEB    19  191.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/19FEB2023.png
50    2023   FEB    20  183.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/20FEB2023.png
51    2023   FEB    21  201.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/21FEB2023.png
52    2023   FEB    22  123.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/22FEB2023.png
53    2023   FEB    23  172.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/23FEB2023.png
54    2023   FEB    24  219.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/24FEB2023.png
55    2023   FEB    25  197.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/25FEB2023.png
56    2023   FEB    26  208.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/26FEB2023.png
57    2023   FEB    27  194.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/27FEB2023.png
58    2023   FEB    28  188.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 02_summ/28FEB2023.png
59    2023   MAR     1  174.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/01MAR2023.png
60    2023   MAR     2  205.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/02MAR2023.png
61    2023   MAR     3  262.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/03MAR2023.png
62    2023   MAR     4  281.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/04MAR2023.png
63    2023   MAR     5  260.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/05MAR2023.png
64    2023   MAR     6  246.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/06MAR2023.png
65    2023   MAR     7  139.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/07MAR2023.png
66    2023   MAR     8  136.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/08MAR2023.png
67    2023   MAR     9  156.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/09MAR2023.png
68    2023   MAR    10  145.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/10MAR2023.png
69    2023   MAR    11  163.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/11MAR2023.png
70    2023   MAR    12  186.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/12MAR2023.png
71    2023   MAR    13  213.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/13MAR2023.png
72    2023   MAR    14  199.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/14MAR2023.png
73    2023   MAR    15  165.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/15MAR2023.png
74    2023   MAR    16  146.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/16MAR2023.png
75    2023   MAR    17  117.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/17MAR2023.png
76    2023   MAR    18  118.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/18MAR2023.png
77    2023   MAR    19   97.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/19MAR2023.png
78    2023   MAR    20   90.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/20MAR2023.png
79    2023   MAR    21   91.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/21MAR2023.png
80    2023   MAR    22   96.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/22MAR2023.png
81    2023   MAR    23   86.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/23MAR2023.png
82    2023   MAR    24   73.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/24MAR2023.png
83    2023   MAR    25   88.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/25MAR2023.png
84    2023   MAR    26   98.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/26MAR2023.png
85    2023   MAR    27   97.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/27MAR2023.png
86    2023   MAR    28  117.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/28MAR2023.png
87    2023   MAR    29  125.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/29MAR2023.png
88    2023   MAR    30  106.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/30MAR2023.png
89    2023   MAR    31   82.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 03_summ/31MAR2023.png
90    2023   APR     1  108.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/01APR2023.png
91    2023   APR     2   93.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/02APR2023.png
92    2023   APR     3   86.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/03APR2023.png
93    2023   APR     4   86.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/04APR2023.png
94    2023   APR     5   87.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/05APR2023.png
95    2023   APR     6   99.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/06APR2023.png
96    2023   APR     7  149.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/07APR2023.png
97    2023   APR     8  182.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/08APR2023.png
98    2023   APR     9  156.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/09APR2023.png
99    2023   APR    10  132.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/10APR2023.png
100   2023   APR    11  112.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/11APR2023.png
101   2023   APR    12  134.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/12APR2023.png
102   2023   APR    13  130.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/13APR2023.png
103   2023   APR    14  126.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/14APR2023.png
104   2023   APR    15  110.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/15APR2023.png
105   2023   APR    16  100.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/16APR2023.png
106   2023   APR    17   95.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/17APR2023.png
107   2023   APR    18  103.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/18APR2023.png
108   2023   APR    19  125.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/19APR2023.png
109   2023   APR    20  106.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/20APR2023.png
110   2023   APR    21   79.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/21APR2023.png
111   2023   APR    22   74.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/22APR2023.png
112   2023   APR    23   86.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/23APR2023.png
113   2023   APR    24   77.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/24APR2023.png
114   2023   APR    25  101.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/25APR2023.png
115   2023   APR    26   94.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/26APR2023.png
116   2023   APR    27   92.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/27APR2023.png
117   2023   APR    28   71.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/28APR2023.png
118   2023   APR    29   81.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/29APR2023.png
119   2023   APR    30   81.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 04_summ/30APR2023.png
120   2023   MAY     1   74.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/01MAY2023.png
121   2023   MAY     2   78.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/02MAY2023.png
122   2023   MAY     3   80.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/03MAY2023.png
123   2023   MAY     4   76.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/04MAY2023.png
124   2023   MAY     5   75.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/05MAY2023.png
125   2023   MAY     6   74.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/06MAY2023.png
126   2023   MAY     7   84.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/07MAY2023.png
127   2023   MAY     8   82.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/08MAY2023.png
128   2023   MAY     9   91.0                                                                          NaN
129   2023   MAY    10  112.0                                                                          NaN
130   2023   MAY    11  121.0                                                                          NaN
131   2023   MAY    12  120.0                                                                          NaN
132   2023   MAY    13   99.0                                                                          NaN
133   2023   MAY    14   52.0                                                                          NaN
134   2023   MAY    15   68.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/15MAY2023.png
135   2023   MAY    16   67.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/16MAY2023.png
136   2023   MAY    17   69.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/17MAY2023.png
137   2023   MAY    18   75.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/18MAY2023.png
138   2023   MAY    19   76.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/19MAY2023.png
139   2023   MAY    20   80.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/20MAY2023.png
140   2023   MAY    21   73.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/21MAY2023.png
141   2023   MAY    22   70.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/22MAY2023.png
142   2023   MAY    23   79.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/23MAY2023.png
143   2023   MAY    24   69.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/24MAY2023.png
144   2023   MAY    25   68.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/25MAY2023.png
145   2023   MAY    26   67.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/26MAY2023.png
146   2023   MAY    27   73.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/27MAY2023.png
147   2023   MAY    28   75.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/28MAY2023.png
148   2023   MAY    29   78.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/29MAY2023.png
149   2023   MAY    30   80.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/30MAY2023.png
150   2023   MAY    31   97.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 05_summ/31MAY2023.png
151   2023   JUN     1   89.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/01JUN2023.png
152   2023   JUN     2   84.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/02JUN2023.png
153   2023   JUN     3   74.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/03JUN2023.png
154   2023   JUN     4   72.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/04JUN2023.png
155   2023   JUN     5   73.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/05JUN2023.png
156   2023   JUN     6   81.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/06JUN2023.png
157   2023   JUN     7   87.0                                                                          NaN
158   2023   JUN     8   89.0                                                                          NaN
159   2023   JUN     9   81.0                                                                          NaN
160   2023   JUN    10   85.0                                                                          NaN
161   2023   JUN    11   85.0                                                                          NaN
162   2023   JUN    12   90.0                                                                          NaN
163   2023   JUN    13   83.0                                                                          NaN
164   2023   JUN    14   78.0                                                                          NaN
165   2023   JUN    15   83.0                                                                          NaN
166   2023   JUN    16   84.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/16JUN2023.png
167   2023   JUN    17   89.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/17JUN2023.png
168   2023   JUN    18   98.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/18JUN2023.png
169   2023   JUN    19   92.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/19JUN2023.png
170   2023   JUN    20   93.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/20JUN2023.png
171   2023   JUN    21  100.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/21JUN2023.png
172   2023   JUN    22   97.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/22JUN2023.png
173   2023   JUN    23   77.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/23JUN2023.png
174   2023   JUN    24   73.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/24JUN2023.png
175   2023   JUN    25   61.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/25JUN2023.png
176   2023   JUN    26   73.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/26JUN2023.png
177   2023   JUN    27   58.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/27JUN2023.png
178   2023   JUN    28   61.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/28JUN2023.png
179   2023   JUN    29   53.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/29JUN2023.png
180   2023   JUN    30   56.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 06_summ/30JUN2023.png
181   2023   JUL     1   67.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/01JUL2023.png
182   2023   JUL     2   54.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/02JUL2023.png
183   2023   JUL     3   62.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/03JUL2023.png
184   2023   JUL     4   65.0  /content/drive/MyDrive/Amajor/img_summ/op_for_summ/23 07_summ/04JUL2023.png

VVIMP

In [ ]:
# full data with missing values inside for img_path


output_path = '/content/drive/MyDrive/Amajor/img_summ/indexed_imgs_with_nulls_.csv'
df_full.to_csv(output_path, index=False)
print(f"DataFrame saved to {output_path}")


#full data of aqi


output_path = '/content/drive/MyDrive/Amajor/img_summ/AQI_full_data_.csv'
df_full[['Year', 'Month', 'Date', 'AQI']].to_csv(output_path, index=False)
print(f"DataFrame saved to {output_path}")


#this data is ready for model

DataFrame saved to /content/drive/MyDrive/Amajor/img_summ/indexed_imgs_with_nulls_.csv
DataFrame saved to /content/drive/MyDrive/Amajor/img_summ/AQI_full_data_.csv

In [ ]:
missing_imgs = df_full[df_full["img_path"].isna()][["Year", "Month", "Date", 'img_path']]

print(missing_imgs)
print(len(missing_imgs))

     Year Month  Date img_path
128  2023   MAY     9      NaN
129  2023   MAY    10      NaN
130  2023   MAY    11      NaN
131  2023   MAY    12      NaN
132  2023   MAY    13      NaN
133  2023   MAY    14      NaN
157  2023   JUN     7      NaN
158  2023   JUN     8      NaN
159  2023   JUN     9      NaN
160  2023   JUN    10      NaN
161  2023   JUN    11      NaN
162  2023   JUN    12      NaN
163  2023   JUN    13      NaN
164  2023   JUN    14      NaN
165  2023   JUN    15      NaN
294  2023   OCT    22      NaN
295  2023   OCT    23      NaN
296  2023   OCT    24      NaN
336  2023   DEC     3      NaN
337  2023   DEC     4      NaN
338  2023   DEC     5      NaN
510  2024   MAY    26      NaN
511  2024   MAY    27      NaN
526  2024   JUN    11      NaN
576  2024   JUL    31      NaN
577  2024   AUG     1      NaN
578  2024   AUG     2      NaN
579  2024   AUG     3      NaN
28